package com.chest.currency.enums;

public enum PermissionName {

	ADD_ROLE("ADD_ROLE", PermissionModule.ADMIN), UPDATE_ROLE("UPDATE_ROLE",
			PermissionModule.ADMIN), VIEW_ROLE("VIEW_ROLE", PermissionModule.ADMIN),

	ADD_USER("ADD_USER", PermissionModule.ADMIN), UPDATE_USER("UPDATE_USER",
			PermissionModule.ADMIN), VIEW_USER("VIEW_USER", PermissionModule.ADMIN),

	UPDATE_LOCKED_USER("UPDATE_LOCKED_USER", PermissionModule.ADMIN), VIEW_LOCKED_USER("UPDATE_LOCKED_USER",
			PermissionModule.ADMIN),

	ADD_ICMC("ADD_ICMC", PermissionModule.ADMIN), UPDATE_ICMC("UPDATE_ICMC",
			PermissionModule.ADMIN), VIEW_ICMC("VIEW_ICMC", PermissionModule.ADMIN),

	ADD_ICMC_REPORT("ADD_ICMC_REPORT", PermissionModule.ADMIN), UPDATE_ICMC_REPORT("UPDATE_ICMC_REPORT",
			PermissionModule.ADMIN), VIEW_ICMC_REPORT("VIEW_ICMC_REPORT", PermissionModule.ADMIN),

	ADD_BRANCH("ADD_BRANCH", PermissionModule.ADMIN), UPDATE_BRANCH("UPDATE_BRANCH",
			PermissionModule.ADMIN), VIEW_BRANCH("VIEW_BRANCH", PermissionModule.ADMIN),

	ADD_DELEGATE_RIGHT("ADD_DELEGATE_RIGHT", PermissionModule.ADMIN), UPDATE_DELEGATE_RIGHT("UPDATE_DELEGATE_RIGHT",
			PermissionModule.ADMIN), VIEW_DELEGATE_RIGHT("VIEW_DELEGATE_RIGHT", PermissionModule.ADMIN),

	ADD_VENDOR("ADD_VENDOR", PermissionModule.ADMIN), UPDATE_VENDOR("UPDATE_VENDOR",
			PermissionModule.ADMIN), VIEW_VENDOR("VIEW_VENDOR", PermissionModule.ADMIN),

	ADD_JURISDICTION("ADD_JURISDICTION", PermissionModule.ADMIN), UPDATE_JURISDICTION("UPDATE_JURISDICTION",
			PermissionModule.ADMIN), VIEW_JURISDICTION("VIEW_JURISDICTION", PermissionModule.ADMIN),

	VIEW_USER_AUDIT_TRAIL("VIEW_USER_AUDIT_TRAIL", PermissionModule.ADMIN),

	ADD_MACHINE_MODEL("ADD_MACHINE_MODEL", PermissionModule.ADMIN), UPDATE_MACHINE_MODEL("UPDATE_MACHINE_MODEL",
			PermissionModule.ADMIN), VIEW_MACHINE_MODEL("VIEW_MACHINE_MODEL", PermissionModule.ADMIN),

	ADD_MACHINE("ADD_MACHINE", PermissionModule.ADMIN), UPDATE_MACHINE("UPDATE_MACHINE",
			PermissionModule.ADMIN), VIEW_MACHINE("VIEW_MACHINE", PermissionModule.ADMIN),

	UPLOAD_HOLIDAY_MASTER("UPLOAD_HOLIDAY_MASTER", PermissionModule.ADMIN), UPDATE_HOLIDAY_MASTER(
			"UPDATE_HOLIDAY_MASTER",
			PermissionModule.ADMIN), VIEW_HOLIDAY_MASTER("VIEW_HOLIDAY_MASTER", PermissionModule.ADMIN),

	VIEW_ACCOUNT_DETAILS("VIEW_ACCOUNT_DETAILS", PermissionModule.ADMIN),

	UPLOAD_SERVICING_BRANCH("UPLOAD_SERVICING_BRANCH", PermissionModule.ADMIN), UPDATE_SERVICING_BRANCH(
			"UPDATE_SERVICING_BRANCH",
			PermissionModule.ADMIN), VIEW_SERVICING_BRANCH("VIEW_SERVICING_BRANCH", PermissionModule.ADMIN),

	ADD_RBI_MASTER("ADD_RBI_MASTER", PermissionModule.ADMIN), UPDATE_RBI_MASTER("UPDATE_RBI_MASTER",
			PermissionModule.ADMIN), VIEW_RBI_MASTER("VIEW_RBI_MASTER", PermissionModule.ADMIN),

	ADD_MACHINE_COMPANY("ADD_MACHINE_COMPANY", PermissionModule.ADMIN), UPDATE_MACHINE_COMPANY("UPDATE_MACHINE_COMPANY",
			PermissionModule.ADMIN), VIEW_MACHINE_COMPANY("VIEW_MACHINE_COMPANY", PermissionModule.ADMIN),

	ADD_DSB_ACCOUNT("ADD_DSB_ACCOUNT", PermissionModule.ADMIN), UPDATE_DSB_ACCOUNT("UPDATE_DSB_ACCOUNT",
			PermissionModule.ADMIN), VIEW_DSB_ACCOUNT("VIEW_DSB_ACCOUNT", PermissionModule.ADMIN),

	ADD_CRA_ACCOUNT("ADD_CRA_ACCOUNT", PermissionModule.ADMIN), UPDATE_CRA_ACCOUNT("UPDATE_CRA_ACCOUNT",
			PermissionModule.ADMIN), VIEW_CRA_ACCOUNT("VIEW_CRA_ACCOUNT", PermissionModule.ADMIN),

	ADD_PRINTER("ADD_PRINTER", PermissionModule.ADMIN), UPDATE_PRINTER("UPDATE_PRINTER",
			PermissionModule.ADMIN), VIEW_PRINTER("VIEW_PRINTER", PermissionModule.ADMIN),

	VIEW_BIN_DASHBOARD("VIEW_BIN_DASHBOARD", PermissionModule.BIN_DASHBOARD),

	ADD_BIN_CAPACITY("ADD_BIN_CAPACITY", PermissionModule.VAULT_MANAGEMENT), UPDATE_BIN_CAPACITY("UPDATE_BIN_CAPACITY",
			PermissionModule.VAULT_MANAGEMENT), VIEW_BIN_CAPACITY("VIEW_BIN_CAPACITY",
					PermissionModule.VAULT_MANAGEMENT),

	ADD_BIN("ADD_BIN", PermissionModule.VAULT_MANAGEMENT), UPDATE_BIN("UPDATE_BIN",
			PermissionModule.VAULT_MANAGEMENT), VIEW_BIN("VIEW_BIN", PermissionModule.VAULT_MANAGEMENT),

	ACCEPT_INDENT("ACCEPT_INDENT", PermissionModule.VAULT_MANAGEMENT), VIEW_INDENT("VIEW_INDENT",
			PermissionModule.VAULT_MANAGEMENT),

	ADD_DEFINE_KEYSET("ADD_DEFINE_KEYSET", PermissionModule.VAULT_MANAGEMENT), UPDATE_DEFINE_KEYSET(
			"UPDATE_DEFINE_KEYSET", PermissionModule.VAULT_MANAGEMENT), VIEW_DEFINE_KEYSET("VIEW_DEFINE_KEYSET",
					PermissionModule.VAULT_MANAGEMENT),

	ADD_ASSIGN_VAULT_CUSTODIAN("ADD_ASSIGN_VAULT_CUSTODIAN",
			PermissionModule.VAULT_MANAGEMENT), UPDATE_ASSIGN_VAULT_CUSTODIAN("UPDATE_ASSIGN_VAULT_CUSTODIAN",
					PermissionModule.VAULT_MANAGEMENT), VIEW_ASSIGN_VAULT_CUSTODIAN("VIEW_ASSIGN_VAULT_CUSTODIAN",
							PermissionModule.VAULT_MANAGEMENT),

	ADD_DAILY_BIN_RECON("ADD_DAILY_BIN_RECON", PermissionModule.VAULT_MANAGEMENT), UPDATE_DAILY_BIN_RECON(
			"UPDATE_DAILY_BIN_RECON", PermissionModule.VAULT_MANAGEMENT), VIEW_DAILY_BIN_RECON("VIEW_DAILY_BIN_RECON",
					PermissionModule.VAULT_MANAGEMENT),

	ADD_PREP_SOILED_REMITTANCE("ADD_PREP_SOILED_REMITTANCE",
			PermissionModule.VAULT_MANAGEMENT), UPDATE_PREP_SOILED_REMITTANCE("UPDATE_PREP_SOILED_REMITTANCE",
					PermissionModule.VAULT_MANAGEMENT), VIEW_PREP_SOILED_REMITTANCE("VIEW_PREP_SOILED_REMITTANCE",
							PermissionModule.VAULT_MANAGEMENT),

	CASH_TRANSFER("CASH_TRANSFER", PermissionModule.VAULT_MANAGEMENT), ACCEPT_AUDITOR_INDENT("ACCEPT_AUDITOR_INDENT",
			PermissionModule.VAULT_MANAGEMENT), DISABLE_BIN("DISABLE_BIN", PermissionModule.VAULT_MANAGEMENT),

	ADD_CIT_CRA_VENDOR("ADD_CIT_CRA_VENDOR", PermissionModule.CIT_CRA_DETAILS), UPDATE_CIT_CRA_VENDOR(
			"UPDATE_CIT_CRA_VENDOR", PermissionModule.CIT_CRA_DETAILS), VIEW_CIT_CRA_VENDOR("VIEW_CIT_CRA_VENDOR",
					PermissionModule.CIT_CRA_DETAILS),

	ADD_CIT_CRA_VEHICLE("ADD_CIT_CRA_VEHICLE", PermissionModule.CIT_CRA_DETAILS), UPDATE_CIT_CRA_VEHICLE(
			"UPDATE_CIT_CRA_VEHICLE", PermissionModule.CIT_CRA_DETAILS), VIEW_CIT_CRA_VEHICLE("VIEW_CIT_CRA_VEHICLE",
					PermissionModule.CIT_CRA_DETAILS),

	ADD_CIT_CRA_DRIVER("ADD_CIT_CRA_DRIVER", PermissionModule.CIT_CRA_DETAILS), UPDATE_CIT_CRA_DRIVER(
			"UPDATE_CIT_CRA_DRIVER", PermissionModule.CIT_CRA_DETAILS), VIEW_CIT_CRA_DRIVER("VIEW_CIT_CRA_DRIVER",
					PermissionModule.CIT_CRA_DETAILS),

	ADD_BRANCH_RECEIPT("ADD_BRANCH_RECEIPT", PermissionModule.CASH_RECEIPT), UPDATE_BRANCH_RECEIPT(
			"UPDATE_BRANCH_RECEIPT",
			PermissionModule.CASH_RECEIPT), VIEW_BRANCH_RECEIPT("VIEW_BRANCH_RECEIPT", PermissionModule.CASH_RECEIPT),

	ADD_DSB("ADD_DSB", PermissionModule.CASH_RECEIPT), UPDATE_DSB("UPDATE_DSB",
			PermissionModule.CASH_RECEIPT), VIEW_DSB("VIEW_DSB", PermissionModule.CASH_RECEIPT),

	ADD_DIVERSION_RECEIPT("ADD_DIVERSION_RECEIPT", PermissionModule.CASH_RECEIPT), UPDATE_DIVERSION_RECEIPT(
			"UPDATE_DIVERSION_RECEIPT", PermissionModule.CASH_RECEIPT), VIEW_DIVERSION_RECEIPT("VIEW_DIVERSION_RECEIPT",
					PermissionModule.CASH_RECEIPT),

	ADD_FRESH_FROM_RBI("ADD_FRESH_FROM_RBI", PermissionModule.CASH_RECEIPT), UPDATE_FRESH_FROM_RBI(
			"UPDATE_FRESH_FROM_RBI",
			PermissionModule.CASH_RECEIPT), VIEW_FRESH_FROM_RBI("VIEW_FRESH_FROM_RBI", PermissionModule.CASH_RECEIPT),

	ADD_OTHER_BANK_RECEIPT("ADD_OTHER_BANK_RECEIPT", PermissionModule.CASH_RECEIPT), UPDATE_OTHER_BANK_RECEIPT(
			"UPDATE_OTHER_BANK_RECEIPT", PermissionModule.CASH_RECEIPT), VIEW_OTHER_BANK_RECEIPT(
					"VIEW_OTHER_BANK_RECEIPT", PermissionModule.CASH_RECEIPT),

	ADD_BOX("ADD_BOX", PermissionModule.CASH_RECEIPT), UPDATE_BOX("UPDATE_BOX",
			PermissionModule.CASH_RECEIPT), VIEW_BOX("VIEW_BOX", PermissionModule.CASH_RECEIPT),

	SAS_UPLOAD("SAS_UPLOAD", PermissionModule.CASH_PAYMENT),

	ADD_DIVERSION_PAYMENT("ADD_DIVERSION_PAYMENT", PermissionModule.CASH_PAYMENT), UPDATE_DIVERSION_PAYMENT(
			"UPDATE_DIVERSION_PAYMENT", PermissionModule.CASH_PAYMENT), VIEW_DIVERSION_PAYMENT("VIEW_DIVERSION_PAYMENT",
					PermissionModule.CASH_PAYMENT),

	ADD_BRANCH_PAYMENT("ADD_BRANCH_PAYMENT", PermissionModule.CASH_PAYMENT), UPDATE_BRANCH_PAYMENT(
			"UPDATE_BRANCH_PAYMENT",
			PermissionModule.CASH_PAYMENT), VIEW_BRANCH_PAYMENT("VIEW_BRANCH_PAYMENT", PermissionModule.CASH_PAYMENT),

	ADD_SOILED_REMITTANCE("ADD_SOILED_REMITTANCE", PermissionModule.CASH_PAYMENT), UPDATE_SOILED_REMITTANCE(
			"UPDATE_SOILED_REMITTANCE", PermissionModule.CASH_PAYMENT), VIEW_SOILED_REMITTANCE("VIEW_SOILED_REMITTANCE",
					PermissionModule.CASH_PAYMENT),

	ADD_SAS("ADD_SAS", PermissionModule.CASH_PAYMENT), UPDATE_SAS("UPDATE_SAS",
			PermissionModule.CASH_PAYMENT), VIEW_SAS("VIEW_SAS", PermissionModule.CASH_PAYMENT),

	ADD_CASH_RELEASED("ADD_CASH_RELEASED", PermissionModule.CASH_PAYMENT), UPDATE_CASH_RELEASED("UPDATE_CASH_RELEASED",
			PermissionModule.CASH_PAYMENT), VIEW_CASH_RELEASED("VIEW_CASH_RELEASED", PermissionModule.CASH_PAYMENT),

	ADD_CRA_PAYMENT("ADD_CRA_PAYMENT", PermissionModule.CASH_PAYMENT), UPDATE_CRA_PAYMENT("UPDATE_CRA_PAYMENT",
			PermissionModule.CASH_PAYMENT), VIEW_CRA_PAYMENT("VIEW_CRA_PAYMENT", PermissionModule.CASH_PAYMENT),

	ADD_OTHER_BANK_PAYMENT("ADD_OTHER_BANK_PAYMENT", PermissionModule.CASH_PAYMENT), UPDATE_OTHER_BANK_PAYMENT(
			"UPDATE_OTHER_BANK_PAYMENT", PermissionModule.CASH_PAYMENT), VIEW_OTHER_BANK_PAYMENT(
					"VIEW_OTHER_BANK_PAYMENT", PermissionModule.CASH_PAYMENT),

	ADD_FORCE_HANDOVER("ADD_FORCE_HANDOVER", PermissionModule.CASH_PAYMENT), UPDATE_FORCE_HANDOVER(
			"UPDATE_FORCE_HANDOVER",
			PermissionModule.CASH_PAYMENT), VIEW_FORCE_HANDOVER("VIEW_FORCE_HANDOVER", PermissionModule.CASH_PAYMENT),

	ADD_OTHER_ICMC_RECEIPT("ADD_OTHER_ICMC_RECEIPT", PermissionModule.CASH_RECEIPT), UPDATE_OTHER_ICMC_RECEIPT(
			"UPDATE_OTHER_ICMC_RECEIPT", PermissionModule.CASH_RECEIPT), VIEW_OTHER_ICMC_RECEIPT(
					"	VIEW_OTHER_ICMC_RECEIPT", PermissionModule.CASH_RECEIPT),

	ADD_PROCESSED_DATA("ADD_PROCESSED_DATA", PermissionModule.PROCESSING_ROOM), UPDATE_PROCESSED_DATA(
			"UPDATE_PROCESSED_DATA", PermissionModule.PROCESSING_ROOM), VIEW_PROCESSED_DATA("VIEW_PROCESSED_DATA",
					PermissionModule.PROCESSING_ROOM),

	ADD_DISCREPANCY("ADD_DISCREPANCY", PermissionModule.PROCESSING_ROOM), UPDATE_DISCREPANCY("UPDATE_DISCREPANCY",
			PermissionModule.PROCESSING_ROOM), VIEW_DISCREPANCY("VIEW_DISCREPANCY", PermissionModule.PROCESSING_ROOM),

	ADD_INDENT("ADD_INDENT", PermissionModule.PROCESSING_ROOM), UPDATE_INDENT("UPDATE_INDENT",
			PermissionModule.PROCESSING_ROOM),

	ADD_MACHINE_ALLOCATION("ADD_MACHINE_ALLOCATION", PermissionModule.PROCESSING_ROOM), UPDATE_MACHINE_ALLOCATION(
			"UPDATE_MACHINE_ALLOCATION", PermissionModule.PROCESSING_ROOM), VIEW_MACHINE_ALLOCATION(
					"VIEW_MACHINE_ALLOCATION", PermissionModule.PROCESSING_ROOM),

	VIEW_BUNDLE_REQUEST_FOR_MACHINE("VIEW_BUNDLE_REQUEST_FOR_MACHINE", PermissionModule.PROCESSING_ROOM),

	ADD_MACHINE_SOFTWARE_UPDATION("ADD_MACHINE_SOFTWARE_UPDATION",
			PermissionModule.PROCESSING_ROOM), UPDATE_MACHINE_SOFTWARE_UPDATION("UPDATE_MACHINE_SOFTWARE_UPDATION",
					PermissionModule.PROCESSING_ROOM), VIEW_MACHINE_SOFTWARE_UPDATION("VIEW_MACHINE_SOFTWARE_UPDATION",
							PermissionModule.PROCESSING_ROOM),

	ADD_MACHINE_DOWNTIME_UPDATION("ADD_MACHINE_DOWNTIME_UPDATION",
			PermissionModule.PROCESSING_ROOM), UPDATE_MACHINE_DOWNTIME_UPDATION("UPDATE_MACHINE_DOWNTIME_UPDATION",
					PermissionModule.PROCESSING_ROOM), VIEW_MACHINE_DOWNTIME_UPDATION("VIEW_MACHINE_DOWNTIME_UPDATION",
							PermissionModule.PROCESSING_ROOM),

	ADD_REPEATABILITY_TEST_INPUT("ADD_REPEATABILITY_TEST_INPUT",
			PermissionModule.PROCESSING_ROOM), UPDATE_REPEATABILITY_TEST_INPUT("UPDATE_REPEATABILITY_TEST_INPUT",
					PermissionModule.PROCESSING_ROOM), VIEW_REPEATABILITY_TEST_INPUT("VIEW_REPEATABILITY_TEST_INPUT",
							PermissionModule.PROCESSING_ROOM),

	ADD_REPEATABILITY_TEST_OUTPUT("ADD_REPEATABILITY_TEST_OUTPUT",
			PermissionModule.PROCESSING_ROOM), UPDATE_REPEATABILITY_TEST_OUTPUT("UPDATE_REPEATABILITY_TEST_OUTPUT",
					PermissionModule.PROCESSING_ROOM), VIEW_REPEATABILITY_TEST_OUTPUT("VIEW_REPEATABILITY_TEST_OUTPUT",
							PermissionModule.PROCESSING_ROOM),

	ADD_FRESH_CURRENCY("ADD_FRESH_CURRENCY", PermissionModule.PROCESSING_ROOM), UPDATE_FRESH_CURRENCY(
			"UPDATE_FRESH_CURRENCY", PermissionModule.PROCESSING_ROOM), VIEW_FRESH_CURRENCY("VIEW_FRESH_CURRENCY",
					PermissionModule.PROCESSING_ROOM),

	ADD_FORWARDED_CRA_PAYMENT("ADD_FORWARDED_CRA_PAYMENT",
			PermissionModule.PROCESSING_ROOM), UPDATE_FORWARDED_CRA_PAYMENT("UPDATE_FORWARDED_CRA_PAYMENT",
					PermissionModule.PROCESSING_ROOM), VIEW_FORWARDED_CRA_PAYMENT("VIEW_FORWARDED_CRA_PAYMENT",
							PermissionModule.PROCESSING_ROOM),

	ADD_MUTILATED_FULLE_VALUE("ADD_MUTILATED_FULLE_VALUE", PermissionModule.PROCESSING_ROOM),

	ADD_SUSPENSE_DISCREPANCY("ADD_SUSPENSE_DISCREPANCY", PermissionModule.PROCESSING_ROOM),

	ADD_SUSPENSE_OPENING_BALANCE("ADD_SUSPENSE_OPENING_BALANCE", PermissionModule.PROCESSING_ROOM),

	ADD_FAKE_NOTE("ADD_FAKE_NOTE", PermissionModule.FAKE_NOTE_MANAGEMENT), UPDATE_FAKE_NOTE("UPDATE_FAKE_NOTE",
			PermissionModule.FAKE_NOTE_MANAGEMENT), VIEW_FAKE_NOTE("VIEW_FAKE_NOTE",
					PermissionModule.FAKE_NOTE_MANAGEMENT),

	MIGRATION("MIGRATION", PermissionModule.MIGRATION),

	VIEW_REPORTS("VIEW_REPORTS", PermissionModule.REPORTS),

	VERIFICATION("VERIFICATION", PermissionModule.VERIFICATION);

	public String val;
	public PermissionModule module;

	PermissionName(String val, PermissionModule module) {
		this.val = val;
		this.module = module;
	}

	public String value() {
		return name();
	}

	public static PermissionName fromValue(String v) {
		return valueOf(v);
	}
}
