-- DROP TABLE IF EXISTS `BIN_CAPACITY_DENOMINATION`;

CREATE TABLE `BIN_CAPACITY_DENOMINATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VAULT_SIZE` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `MAX_BUNDLE_CAPACITY` decimal(10,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `BIN_MASTER`;

CREATE TABLE `BIN_MASTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_PRIORITY` varchar(250) DEFAULT NULL,
  `SECOND_PRIORITY` varchar(250) DEFAULT NULL,
  `THIRD_PRIORITY` varchar(250) DEFAULT NULL,
  `FOURTH_PRIORITY` varchar(250) DEFAULT NULL,
  `FIFTH_PRIORITY` varchar(250) DEFAULT NULL,
  `LOCA_PRIORITY` int(11) DEFAULT NULL,
  `BIN_NUM` varchar(250) DEFAULT NULL,
  `IS_ALLOCATED` int(11) DEFAULT '0',
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `VAULT_SIZE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `BIN_TRANSACTION`;

CREATE TABLE `BIN_TRANSACTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `MAX_CAPACITY` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `RECEIVE_BUNDLE` decimal(10,2) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(19,2) DEFAULT 0,
  `CASH_SOURCE` varchar(20) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  `CASH_TYPE` varchar(20) DEFAULT NULL,
  `VERIFIED` varchar(20) DEFAULT NULL,
  `RBI_ORDER_NO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `BIN_TYPE_COLOR`;

CREATE TABLE `BIN_TYPE_COLOR` (
  `ID` bigint(11) NOT NULL,
  `BIN_TYPE` varchar(100) DEFAULT NULL,
  `COLOR_CODE` varchar(45) DEFAULT NULL,
  `HTML_COLOR_CODE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `BRANCH`;

CREATE TABLE `BRANCH` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SOL_ID` varchar(45) DEFAULT NULL,
  `BRANCH_NAME` varchar(45) DEFAULT NULL,
  `SERVICING_ICMC` varchar(45) DEFAULT NULL,
  `JURISDICTION_ICMC` varchar(45) DEFAULT NULL,
  `RBI_NAME` varchar(45) DEFAULT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `PINCODE` int(11) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `BRANCH_RECEIPT`;

CREATE TABLE `BRANCH_RECEIPT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SOL_ID` varchar(20) DEFAULT NULL,
  `BRANCH` varchar(150) DEFAULT NULL,
  `SR_NUMBER` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `FILEPATH` varchar(500) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(150) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(19,2) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `CIT_CRA_DRIVER`;

CREATE TABLE `CIT_CRA_DRIVER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VENDOR_NAME` varchar(45) DEFAULT NULL,
  `VEHICLE_NUMBER` varchar(45) DEFAULT NULL,
  `DRIVER_NAME` varchar(45) DEFAULT NULL,
  `LICENSE_NUMBER` varchar(45) DEFAULT NULL,
  `LICENSE_ISSUED_STATE` varchar(45) DEFAULT NULL,
  `LICENSE_ISSUE_DATE` date DEFAULT NULL,
  `LICENSE_EXPIRY_DATE` date DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `CIT_CRA_VEHICLE`;

CREATE TABLE `CIT_CRA_VEHICLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VENDOR_NAME` varchar(45) DEFAULT NULL,
  `VEHICLE_NUMBER` varchar(45) DEFAULT NULL,
  `BOUGHT_DATE` date DEFAULT NULL,
  `REGISTRATION_CITY` varchar(45) DEFAULT NULL,
  `VEHICLE_INSURANCE` varchar(45) DEFAULT NULL,
  `FITNESS_EXPIRY_DATE` date DEFAULT NULL,
  `POLLUTION_EXPIRY_DATE` date DEFAULT NULL,
  `PERMIT_DATE` date DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `CIT_CRA_VENDOR`;

CREATE TABLE `CIT_CRA_VENDOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `TYPE_ONE` varchar(45) DEFAULT NULL,
  `TYPE_TWO` varchar(45) DEFAULT NULL,
  `TYPE_THREE` varchar(45) DEFAULT NULL,
  `FPR_NAME` varchar(45) DEFAULT NULL,
  `FPR_NUMBER` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `CIT_CRA_VENDOR_ICMC_ASSO`;

CREATE TABLE `CIT_CRA_VENDOR_ICMC_ASSO` (
  `VENDOR_ID` bigint(20) DEFAULT NULL,
  `ICMC_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `DIVERSION_IRV`;

CREATE TABLE `DIVERSION_IRV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_DATE` date DEFAULT NULL,
  `RBI_ORDER_NO` varchar(45) DEFAULT NULL,
  `EXPIRY_DATE` date DEFAULT NULL,
  `BANK_NAME` varchar(45) DEFAULT NULL,
  `APPROVED_CC` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `CATEGORY` varchar(45) DEFAULT NULL,
  `FILEPATH` varchar(245) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `DSB`;

CREATE TABLE `DSB` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `PROCESSING_OR_VAULT` varchar(45) DEFAULT NULL,
  `FILEPATH` varchar(245) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `RECEIPT_SEQUENCE` int(11) DEFAULT NULL,
  `RECEIPT_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `FRESH_FROM_RBI`;

CREATE TABLE `FRESH_FROM_RBI` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `NOTES_OR_COINS` varchar(45) DEFAULT NULL,
  `ORDER_DATE` date DEFAULT NULL,
  `RBI_ORDER_NO` varchar(45) DEFAULT NULL,
  `VEHICLE_NUMBER` varchar(45) DEFAULT NULL,
  `POTDAR_NAME` varchar(45) DEFAULT NULL,
  `ESCORT_OFFICER_NAME` varchar(45) DEFAULT NULL,
  `FILEPATH` varchar(245) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `BIN_OR_BOX` varchar(45) DEFAULT NULL,
  `POTDAR_STATUS` varchar(45) DEFAULT NULL,
  `NO_OF_BAGS` int(11) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  `CASH_SOURCE` varchar(20) DEFAULT NULL,
  `CASH_TYPE` varchar(20) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(19, 2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `HOLIDAY_MASTER`;

CREATE TABLE `HOLIDAY_MASTER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOLIDAY_NAME` varchar(110) DEFAULT NULL,
  `HOLIDAY_TYPE` varchar(45) DEFAULT NULL,
  `HOLIDAY_DATE` varchar(45) DEFAULT NULL,
  `ANDAMAN_AND_NICOBAR_ISLANDS` varchar(45) DEFAULT NULL,
  `ANDHRA_PRADESH` varchar(45) DEFAULT NULL,
  `ARUNACHAL_PRADESH` varchar(45) DEFAULT NULL,
  `ASSAM` varchar(45) DEFAULT NULL,
  `BIHAR` varchar(45) DEFAULT NULL,
  `CHANDIGARH` varchar(45) DEFAULT NULL,
  `CHHATTISGARH` varchar(45) DEFAULT NULL,
  `DAMAN_AND_DIU` varchar(45) DEFAULT NULL,
  `DELHI` varchar(45) DEFAULT NULL,
  `GOA` varchar(45) DEFAULT NULL,
  `GUJARAT` varchar(45) DEFAULT NULL,
  `HIMACHAL_PRADESH` varchar(45) DEFAULT NULL,
  `HARYANA` varchar(45) DEFAULT NULL,
  `JHARKHAND` varchar(45) DEFAULT NULL,
  `JAMMU_AND_KASHMIR` varchar(45) DEFAULT NULL,
  `KARNATAKA` varchar(45) DEFAULT NULL,
  `KERALA` varchar(45) DEFAULT NULL,
  `MAHARASHTRA` varchar(45) DEFAULT NULL,
  `MEGHALAYA` varchar(45) DEFAULT NULL,
  `MANIPUR` varchar(45) DEFAULT NULL,
  `MADHYA_PRADESH` varchar(45) DEFAULT NULL,
  `MIZORAM` varchar(45) DEFAULT NULL,
  `NAGALAND` varchar(45) DEFAULT NULL,
  `ORISSA` varchar(45) DEFAULT NULL,
  `PUNJAB` varchar(45) DEFAULT NULL,
  `PONDICHERRY` varchar(45) DEFAULT NULL,
  `RAJASTHAN` varchar(45) DEFAULT NULL,
  `SIKKIM` varchar(45) DEFAULT NULL,
  `TAMIL_NADU` varchar(45) DEFAULT NULL,
  `TRIPURA` varchar(45) DEFAULT NULL,
  `UTTAR_PRADESH` varchar(45) DEFAULT NULL,
  `UTTARANCHAL` varchar(45) DEFAULT NULL,
  `WEST_BENGAL` varchar(45) DEFAULT NULL,
  `DADRA_AND_NAGAR_HAVELI` varchar(45) DEFAULT NULL,
  `LAKSHADWEEP` varchar(45) DEFAULT NULL,
  `TELANGANA` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ICMC`;

CREATE TABLE `ICMC` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `LINK_BRANCH_SOLID` varchar(45) DEFAULT NULL,
  `RBI_NAME` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(250) DEFAULT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `PINCODE` int(11) DEFAULT NULL,
  `STATUS` varchar(45) CHARACTER SET utf8 DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ICMC_REPORT`;

CREATE TABLE `ICMC_REPORT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOM_REPORT_TYPE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `REASON_FOR_DELETION` varchar(45) DEFAULT NULL,
  `APPROVAL_FOR_DELETION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ICMC_REPORT_ASSOCIATION`;

CREATE TABLE `ICMC_REPORT_ASSOCIATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPORT_ID` int(11) DEFAULT NULL,
  `REPORT_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `INDENT`;

CREATE TABLE `INDENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT '1',
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(10,2) DEFAULT 0,
  `BIN_CATEGORY_TYPE` varchar(45) DEFAULT NULL,
  `RBI_ORDER_NO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `JURISDICTION`;

CREATE TABLE `JURISDICTION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SOL_ID` int(11) DEFAULT NULL,
  `BRANCH_NAME` varchar(45) DEFAULT NULL,
  `ICMC_NAME` varchar(45) DEFAULT NULL,
  `JURISDICTION` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `PINCODE` int(11) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `MACHINE_ALLOCATION`;

CREATE TABLE `MACHINE_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(19,0) DEFAULT NULL,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `ISSUED_BUNDLE` decimal(19,0) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  `IS_MANUAL` varchar(45) DEFAULT NULL,
  `PENDING_BUNDLE` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `RETURN_BACK_TO_VAULT` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `PROCESS`;

CREATE TABLE `PROCESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` int(11) DEFAULT '1',
  `FILEPATH` varchar(250) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `CASH_SOURCE` varchar(20) DEFAULT NULL,
  `PROCESSED_BY` varchar(20) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `SAS`;


CREATE TABLE `SAS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SR_NO` varchar(45) DEFAULT NULL,
  `SOL_ID` varchar(250) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `TOTAL_VALUE` decimal(10,2) DEFAULT NULL,
  `TOTAL_VALUE_OF_COINS_RS_10` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_COINS_RS_5` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_COINS_RS_2` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_COINS_RS_1` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_1_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_10_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_100_F` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_1000_F` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_2_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_20_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_5_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_50_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_500_F` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_1_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_10_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_100_I` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_1000_I` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_2_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_20_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_50_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_5_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_500_I` decimal(12,2) DEFAULT '0.00',
  `DATE_OF_DISPATCH` varchar(45) DEFAULT NULL,
  `ACTION_TAKEN` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `STATUS` int(11) DEFAULT '1',
  `ICMC_ID` decimal(10,0) DEFAULT NULL,
  `RELEASED_NOTES_1_I` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_1_F` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_10_I` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_10_F` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_100_I` decimal(12,2) DEFAULT '0.00',
  `RELEASED_NOTES_100_F` decimal(12,2) DEFAULT '0.00',
  `RELEASED_NOTES_1000_I` decimal(12,2) DEFAULT '0.00',
  `RELEASED_NOTES_1000_F` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_100_A` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_500_A` decimal(12,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_1000_A` decimal(12,2) DEFAULT '0.00',
  `FILE_NAME` varchar(45) DEFAULT NULL,
  `RELEASED_NOTES_100_A` decimal(12,2) DEFAULT '0.00',
  `RELEASED_NOTES_500_A` decimal(12,2) DEFAULT '0.00',
  `RELEASED_NOTES_1000_A` decimal(12,2) DEFAULT '0.00',
  `ENABLE_DISABLE` int(11) DEFAULT NULL,
  `RELEASED_COINS_1` decimal(10,2) DEFAULT '0.00',
  `RELEASED_COINS_2` decimal(10,2) DEFAULT '0.00',
  `RELEASED_COINS_5` decimal(10,2) DEFAULT '0.00',
  `RELEASED_COINS_10` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_2000_I` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_2000_A` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_2000_F` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_2000_A` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_2000_I` decimal(10,2) DEFAULT '0.00',
  `RELEASED_NOTES_2000_F` decimal(10,2) DEFAULT '0.00',
  `TOTAL_VALUE_OF_NOTES_RS_200_I` decimal(10,2) DEFAULT NULL,
  `TOTAL_VALUE_OF_NOTES_RS_200_A` decimal(10,2) DEFAULT NULL,
  `TOTAL_VALUE_OF_NOTES_RS_200_F` decimal(10,2) DEFAULT NULL,
  `RELEASED_NOTES_200_A` decimal(10,2) DEFAULT NULL,
  `RELEASED_NOTES_200_I` decimal(10,2) DEFAULT NULL,
  `RELEASED_NOTES_200_F` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- DROP TABLE IF EXISTS `SAS_ALLOCATION`;

CREATE TABLE `SAS_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CASH_TYPE` varchar(20) DEFAULT NULL,
  `PARENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `SERVICING_BRANCH`;

CREATE TABLE `SERVICING_BRANCH` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ICMC_NAME` varchar(45) DEFAULT NULL,
  `SOL_ID` int(11) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `RBI_JI` varchar(45) DEFAULT NULL,
  `RBI_SI` varchar(45) DEFAULT NULL,
  `CATEGORY` varchar(45) DEFAULT NULL,
  `RBI_ICMC` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `SOILED_REMITTANCE`;

CREATE TABLE `SOILED_REMITTANCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_DATE` date DEFAULT NULL,
  `REMITTANCE_ORDER_NO` decimal(19,0) DEFAULT NULL,
  `APPROVED_REMITTANCE_DATE` date DEFAULT NULL,
  `NOTES` varchar(45) DEFAULT NULL,
  `TYPES` varchar(45) DEFAULT NULL,
  `VEHICLE_NUMBER` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `SOILED_REMITTANCE_ALLOCATION`;

CREATE TABLE `SOILED_REMITTANCE_ALLOCATION` (
  `ID` bigint(20) NOT NULL,
  `SOILED_REMITTANCE_ID` bigint(20) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `BOX` varchar(45) DEFAULT NULL,
  `WEIGHT` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `FILEPATH` varchar(500) DEFAULT NULL,
  `PENDING_BUNDLE` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `UI_USER`;

CREATE TABLE `UI_USER` (
  `ID` varchar(32) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `PASSWORD` varchar(250) DEFAULT NULL,
  `PASSWORD_HASH` varchar(45) DEFAULT NULL,
  `PASSWORD_SALT` varchar(45) DEFAULT NULL,
  `ZONE_ID` varchar(45) DEFAULT NULL,
  `REGION_ID` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_DATETIME` timestamp NULL DEFAULT NULL,
  `UPDATED_DATETIME` timestamp NULL DEFAULT NULL,
  `LAST_AUTH_OK` varchar(45) DEFAULT NULL,
  `LAST_AUTH_FAIL` timestamp NULL DEFAULT NULL,
  `FAILED_LOGONS` int(11) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `ROLE_ID` varchar(45) DEFAULT NULL,
  `IS_ACCOUNT_LOCKED` char(1) DEFAULT NULL,
  `ICMC_PRINTER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `VENDOR`;

CREATE TABLE `VENDOR` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `PINCODE` int(11) DEFAULT NULL,
  `PHONE_NUMBER` bigint(20) DEFAULT NULL,
  `EMAIL_ID` varchar(45) DEFAULT NULL,
  `PF_REG_NUMBER` varchar(45) DEFAULT NULL,
  `ESIC_REG_NUMBER` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ZONE_MASTER`;

CREATE TABLE `ZONE_MASTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `FRESH_CURRENCY`;

CREATE TABLE `FRESH_CURRENCY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_NO` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(19,2) DEFAULT NULL,
  `TOTAL_VALUE` decimal(19,2) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `ASSIGN_VAULT_CUSTODIAN`;

CREATE TABLE `ASSIGN_VAULT_CUSTODIAN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` varchar(45) DEFAULT NULL,
  `CUSTODIAN` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `KEY_SET`;

CREATE TABLE `KEY_SET` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CUSTODIAN` varchar(45) DEFAULT NULL,
  `KEY_NUMBER` varchar(45) DEFAULT NULL,
  `LOCATION_OF_LOCK` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `REPEATABILITY_TEST_INPUT`;

CREATE TABLE `REPEATABILITY_TEST_INPUT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `MACHINE_SERIAL_NO` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `DENOMINATION` varchar(45) DEFAULT NULL,
  `BUNDLE` decimal(19,2) DEFAULT NULL,
  `BIN_NO` varchar(45) DEFAULT NULL,
  `TOTAL_NOTES` decimal(19,2) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `REPEATABILITY_TEST_OUTPUT`;

CREATE TABLE `REPEATABILITY_TEST_OUTPUT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_NO` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `DENOMINATION` varchar(45) DEFAULT NULL,
  `BUNDLE` varchar(45) DEFAULT NULL,
  `TOTAL_VALUE` varchar(45) DEFAULT NULL,
  `BIN_NO` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `TYPEVALUE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ORV`;

CREATE TABLE `ORV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SR` varchar(45) DEFAULT NULL,
  `SACK_LOCK_NUMBER` varchar(45) DEFAULT NULL,
  `SOL_ID` varchar(20) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `VENDOR` varchar(45) DEFAULT NULL,
  `CUSTODIAN` varchar(45) DEFAULT NULL,
  `VEHICLE` varchar(45) DEFAULT NULL,
  `STATUS` int(11) DEFAULT '1',
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `ORV_ALLOCATION`;

CREATE TABLE `ORV_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORV_ID` bigint(20) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `DIVERSION_ORV`;

CREATE TABLE `DIVERSION_ORV` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_DATE` date DEFAULT NULL,
  `RBI_ORDER_NO` int(11) DEFAULT NULL,
  `EXPIRY_DATE` date DEFAULT NULL,
  `BANK_NAME` varchar(45) DEFAULT NULL,
  `APPROVED_CC` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `DIVERSION_ORV_ALLOCATION`;

CREATE TABLE `DIVERSION_ORV_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DIVERSION_ORV_ID` bigint(20) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `CATEGORY` varchar(45) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `PENDING_BUNDLE` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `CASH_RELEASED`;

CREATE TABLE `CASH_RELEASED` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `SOL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `FAKE_NOTE`;

CREATE TABLE `FAKE_NOTE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FAKE_NOTE_DATE` date DEFAULT NULL,
  `SOL_ID` int(11) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `FAKE_NOTE_SERIAL_NUMBER` varchar(45) DEFAULT NULL,
  `CUST_TELLER_CAM` varchar(45) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `ACCOUNT_DETAIL`;

CREATE TABLE `ACCOUNT_DETAIL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACTIVITY` varchar(45) DEFAULT NULL,
  `USAGE` varchar(45) DEFAULT NULL,
  `DEBIT_OR_CREDIT` varchar(45) DEFAULT NULL,
  `ACCOUNT_DETAILS` varchar(45) DEFAULT NULL,
  `BRANCH_DETAILS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `DELEGATE_RIGHT`;

CREATE TABLE `DELEGATE_RIGHT` (	
 `ID` bigint(20) NOT NULL AUTO_INCREMENT,
 `USER_ID` VARCHAR(45) DEFAULT NULL, 
 `ROLE` VARCHAR(45) DEFAULT NULL,
 `STATUS` VARCHAR(45) DEFAULT NULL,
 `PERIOD_FROM` DATETIME DEFAULT NULL, 
 `PERIOD_TO` DATETIME DEFAULT NULL, 
 `ICMC_ID` DECIMAL(19,0) DEFAULT NULL, 
 `INSERT_BY` VARCHAR(45) DEFAULT NULL, 
 `UPDATE_BY` VARCHAR(45) DEFAULT NULL, 
 `INSERT_TIME` DATETIME DEFAULT NULL, 
 `UPDATE_TIME` DATETIME DEFAULT NULL,
 PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `DISCREPANCY`;

CREATE TABLE `DISCREPANCY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_NUMBER` int(11) DEFAULT NULL,
  `DISCREPANCY_DATE` date DEFAULT NULL,
  `SOL_ID` int(11) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `FILE_PATH` varchar(500) DEFAULT NULL,
  `ACCOUNT_TELLER_CAM` varchar(45) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(45) DEFAULT NULL,
  `DISCREPANCY_TYPE` varchar(45) DEFAULT NULL,
  `MUTIL_TYPE` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `DISCREPANCY_ALLOCATION`;

CREATE TABLE `DISCREPANCY_ALLOCATION` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `DISCREPANCY_ID` bigint(11) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `NOTE_SERIAL_NUMBER` varchar(45) DEFAULT NULL,
  `DIS_VALUE` int(11) DEFAULT NULL,
  `SR_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `REMARKS` varchar(45) DEFAULT NULL,
  `DISCREPANCY_TYPE` varchar(45) DEFAULT NULL,
  `MUTIL_TYPE` varchar(45) DEFAULT NULL,
  `NUMBER_OF_NOTES` int(11) DEFAULT NULL,
  `PRINT_YEAR` int(11) DEFAULT NULL,
  `DATE_ON_SHRINK_WRAP` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `MACHINE`;

CREATE TABLE `MACHINE` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(45) DEFAULT NULL,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `ASSET_CODE` varchar(45) DEFAULT NULL,
  `MACHINE_SI_NO` varchar(45) DEFAULT NULL,
  `MODEL_TYPE` varchar(45) DEFAULT NULL,
  `STANDARD_PRODUCTIVITY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` date DEFAULT NULL,
  `UPDATE_TIME` date DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `SAP` int(11) DEFAULT NULL,
  `MAP` int(11) DEFAULT NULL,
  `OSAP` int(11) DEFAULT NULL,
  `PM_DATE` date DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `MACHINE_MODEL`;

CREATE TABLE `MACHINE_MODEL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `MACHINE_MODEL_TYPE` varchar(45) DEFAULT NULL,
  `STANDARD_PRODUCTIVITY` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `MACHINE_SOFTWARE_UPDATION`;

CREATE TABLE `MACHINE_SOFTWARE_UPDATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `SAP` int(11) DEFAULT NULL,
  `MAP` int(11) DEFAULT NULL,
  `OSAP` int(11) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `ASSET_CODE` varchar(45) DEFAULT NULL,
  `MACHINE_SI_NO` varchar(45) DEFAULT NULL,
  `MODEL_TYPE` varchar(45) DEFAULT NULL,
  `STANDARD_PRODUCTIVITY` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `MACHINE_DOWNTIME_UPDATION`;

CREATE TABLE `MACHINE_DOWNTIME_UPDATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MACHINE_DOWN_DATE_FROM` datetime DEFAULT NULL,
  `MACHINE_NO` int(11) DEFAULT NULL,
  `MACHINE_DOWN_DATE_TO` datetime DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `REMARKS` varchar(45) DEFAULT NULL,
  `DOWNTIME_REASON` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `UI_ROLE`;

CREATE TABLE `UI_ROLE` (
  `ID` varchar(32) NOT NULL,
  `ICMC_ACCESS` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `UI_ROLE_PERMISSION`;

CREATE TABLE `UI_ROLE_PERMISSION` (
  `ROLE_NAME` VARCHAR(32) NOT NULL,
  `FUNCTION_PERMISSION` varchar(45) DEFAULT NULL
);

-- DROP TABLE IF EXISTS `CRA_ACCOUNT_DETAIL`;

CREATE TABLE `CRA_ACCOUNT_DETAIL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CRA_VENDOR_NAME` varchar(45) DEFAULT NULL,
  `MSP_NAME` varchar(45) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `DSB_ACCOUNT_DETAIL`;

CREATE TABLE `DSB_ACCOUNT_DETAIL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `DSB_VENDOR_NAME` varchar(45) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `RBI_MASTER`;

CREATE TABLE `RBI_MASTER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RBI_NAME` varchar(45) NOT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `ADDRESS` varchar(80) DEFAULT NULL,
  `PIN_NO` int(15) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
   PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `CRA`;

CREATE TABLE `CRA` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SR_NO` varchar(45) DEFAULT NULL,
  `SOL_ID` varchar(45) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `VENDOR` varchar(45) DEFAULT NULL,
  `MSP_NAME` varchar(45) DEFAULT NULL,
  `ACCOUNT_NUMBER` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `CRA_ALLOCATION`;

CREATE TABLE `CRA_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRA_ID` bigint(20) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(19,2) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `TOTAL` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `VAULT` decimal(19,2) DEFAULT NULL,
  `FORWARD` decimal(19,2) DEFAULT NULL,
  `PENDING_REQUESTED_BUNDLE` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `MACHINE_COMPANY`;

CREATE TABLE `MACHINE_COMPANY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `PURCHASE_DATE` date DEFAULT NULL,
  `PHONE_NUMBER` bigint(11) DEFAULT NULL,
  `ADDRESS` varchar(80) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `BANK_RECEIPT`;

CREATE TABLE `BANK_RECEIPT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` DECIMAL(10,2) DEFAULT NULL,
  `TOTAL` DECIMAL(19,2) DEFAULT NULL,
  `BIN_NUM` varchar(20) DEFAULT NULL,
  `FILE_PATH` VARCHAR(500) DEFAULT NULL,
  `ICMC_ID` DECIMAL(19,0) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `BANK_NAME` VARCHAR(45) DEFAULT NULL,
  `RTGS_UTR_NO` varchar(45) DEFAULT NULL,
  `SOL_ID` VARCHAR(20) DEFAULT NULL,
  `BRANCH` VARCHAR(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `OTHER_BANK`;

CREATE TABLE `OTHER_BANK` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BANK_NAME` varchar(45) DEFAULT NULL,
  `RTGS_UTR_NO` varchar(45) DEFAULT NULL,
  `SOL_ID` varchar(45) DEFAULT NULL,
  `BRANCH` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `OTHER_BANK_ALLOCATION`;

CREATE TABLE `OTHER_BANK_ALLOCATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `OTHER_BANK_ID` bigint(20) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(19,2) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `TOTAL` decimal(19,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `PENDING_BUNDLE` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `UI_USER_PASSWORD_RESET`;

CREATE TABLE `UI_USER_PASSWORD_RESET` (
  `USER_ID` varchar(32) NOT NULL,
  `TOKEN` varchar(45) NOT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_DATETIME` datetime DEFAULT NULL NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL NULL
);

-- DROP TABLE IF EXISTS `COINS_SEQUENCE`;

CREATE TABLE `COINS_SEQUENCE` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `SEQUENCE` int(11) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `FORWARD_BUNDLE_FOR_CRA_PAYMENT`;

CREATE TABLE `FORWARD_BUNDLE_FOR_CRA_PAYMENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `PENDING_REQUESTED_BUNDLE` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `PROCESS_BUNDLE_FOR_CRA_PAYMENT`;

CREATE TABLE `PROCESS_BUNDLE_FOR_CRA_PAYMENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `FILEPATH` varchar(500) DEFAULT NULL,
  `CASH_SOURCE` varchar(20) DEFAULT NULL,
  `PENDING_REQUESTED_BUNDLE` decimal(19,2) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `CRA_PAYMENT`;

CREATE TABLE `CRA_PAYMENT` (
  `ID` bigint(20) NOT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- DROP TABLE IF EXISTS `BOX_MASTER`;

CREATE TABLE `BOX_MASTER` (
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `BOX_NAME` varchar(45) DEFAULT NULL,
  `MAX_CAPACITY` decimal(10,0) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  `IS_ALLOCATED` int(11) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `BIN_TRANSACTION_BOD_BALANCE`;

CREATE TABLE `BIN_TRANSACTION_BOD_BALANCE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION_1` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_2` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_5` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_10` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_20` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_50` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_100` decimal(10,2) DEFAULT NULL,
   `DENOMINATION_200` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_500` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_1000` decimal(10,2) DEFAULT NULL,
  `DENOMINATION_2000` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `CASH_TYPE` varchar(45) DEFAULT NULL,
  `CURRENT_VERSION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

-- DROP TABLE IF EXISTS `ICMC_PRINTER`;

CREATE TABLE ICMC_PRINTER (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRINTER_NAME` varchar(45) DEFAULT NULL,
  `PRINTER_IP` varchar(45) DEFAULT NULL,
  `PORT` decimal(19,0) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);


-- Creating Tables corresponding to view's created in Oracle

DROP TABLE IF EXISTS `ZONE_WISE_SUMMARY`;

CREATE TABLE ZONE_WISE_SUMMARY (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TOTAL_VALUE` decimal(19,2) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `REGION_WISE_SUMMARY`;

CREATE TABLE REGION_WISE_SUMMARY (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TOTAL_VALUE` decimal(19,2) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `ZONE` varchar(45) DEFAULT NULL,
  `REGION` varchar(45) DEFAULT NULL,
  `CASH_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `MUTILATED` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(45) DEFAULT NULL,
  `NOTES` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `MUTILATED` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(45) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `MUTILATED_INDENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(10,2) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

desc BIN_TRANSACTION;

create table CASH_TRANSFER
(
ID bigint(20) not null auto_increment primary key,
TRANSFER_TYPE varchar(50),
FROM_BIN_OR_BOX varchar(50),
TO_BIN_OR_BOX varchar(50),
RECEIVE_BUNDLE decimal(10,2),
DENOMINATION int(11),
REMARKS varchar(100),
ICMC_ID decimal(19,0),
INSERT_TIME datetime,
UPDATE_TIME datetime,
INSERT_BY varchar(45),
UPDATE_BY varchar(45)
);

CREATE TABLE `AUDITOR_INDENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `DENOMINATION` int(11) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `BIN_TYPE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `PENDING_BUNDLE_REQUEST` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `AUDITOR_PROCESS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DENOMINATION` int(11) DEFAULT NULL,
  `CURRENCY_TYPE` varchar(45) DEFAULT NULL,
  `BUNDLE` decimal(10,2) DEFAULT NULL,
  `TOTAL` decimal(10,0) DEFAULT NULL,
  `BIN_NUM` varchar(45) DEFAULT NULL,
  `ICMC_ID` decimal(19,0) DEFAULT NULL,
  `STATUS` int(11) DEFAULT '1',
  `FILEPATH` varchar(250) DEFAULT NULL,
  `INSERT_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `INSERT_BY` varchar(45) DEFAULT NULL,
  `UPDATE_BY` varchar(45) DEFAULT NULL,
  `BIN_CATEGORY_TYPE` varchar(20) DEFAULT NULL,
  `CASH_SOURCE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
