
USE currency;

DROP TABLE BIN_CAPACITY_DENOMINATION;

DROP SEQUENCE BIN_CAP_DENOM_SEQ;

DROP TABLE BIN_MASTER;

DROP SEQUENCE BIN_MASTER_SEQ;

DROP TABLE BIN_TRANSACTION;

DROP SEQUENCE BIN_TRANSACTION_SEQ;

DROP TABLE BIN_TYPE_COLOR;

DROP SEQUENCE BIN_TYPE_COLOR_SEQ;

DROP TABLE BRANCH;

DROP SEQUENCE BRANCH_SEQ;

DROP TABLE BRANCH_RECEIPT;

DROP SEQUENCE BRANCH_RECEIPT_SEQ;

DROP TABLE CIT_CRA_DRIVER;

DROP SEQUENCE CIT_CRA_DRIVER_SEQ;

DROP TABLE CIT_CRA_VEHICLE;

DROP SEQUENCE CIT_CRA_VEHICLE_SEQ;

DROP TABLE CIT_CRA_VENDOR;

DROP SEQUENCE CIT_CRA_VENDOR_SEQ;

DROP TABLE CIT_CRA_VENDOR_ICMC_ASSO;

DROP TABLE DIVERSION_IRV;

DROP SEQUENCE DIVERSION_IRV_SEQ;

DROP TABLE DSB;

DROP SEQUENCE DSB_SEQ;

DROP TABLE FRESH_FROM_RBI;

DROP SEQUENCE FRESH_FROM_RBI_SEQ;

DROP TABLE HOLIDAY_MASTER;

DROP SEQUENCE HOLIDAY_MASTER_SEQ;

DROP TABLE ICMC;

DROP SEQUENCE ICMC_SEQ;

DROP TABLE ICMC_REPORT;

DROP SEQUENCE ICMC_REPORT_SEQ;

DROP TABLE ICMC_REPORT_ASSOCIATION;

DROP SEQUENCE ICMC_REPORT_ASSOCIATION_SEQ;

DROP TABLE INDENT;

DROP SEQUENCE INDENT_SEQ;

DROP TABLE JURISDICTION;

DROP SEQUENCE JURISDICTION_SEQ;

DROP TABLE MACHINE_ALLOCATION;

DROP SEQUENCE MACHINE_ALLOCATION_SEQ;

DROP TABLE PROCESS;

DROP SEQUENCE PROCESS_SEQ;

DROP TABLE SAS;

DROP SEQUENCE SAS_SEQ;

DROP TABLE SAS_ALLOCATION;

DROP SEQUENCE SAS_ALLOCATION_SEQ;

DROP TABLE SERVICING_BRANCH;

DROP SEQUENCE SERVICING_BRANCH_SEQ;

DROP TABLE SOILED_REMITTANCE;

DROP SEQUENCE SOILED_REMITTANCE_SEQ;

DROP TABLE SOILED_REMITTANCE_ALLOCATION;

DROP SEQUENCE SOILED_REMIT_ALLOC_SEQ;

DROP TABLE UI_USER;

DROP TABLE USER_ROLE_ASSOCIATION;

DROP TABLE VENDOR;

DROP SEQUENCE VENDOR_SEQ;

DROP TABLE ZONE_MASTER;

DROP SEQUENCE ZONE_MASTER_SEQ;

DROP TABLE ICMC_RECEIPT;

DROP SEQUENCE ICMC_RECEIPT_SEQ;

DROP TABLE FRESH_CURRENCY;

DROP SEQUENCE FRESH_CURRENCY_SEQ;

DROP TABLE ASSIGN_VAULT_CUSTODIAN;

DROP SEQUENCE ASSIGN_VAULT_CUSTODIAN_SEQ;

DROP TABLE KEY_SET;

DROP SEQUENCE KEY_SET_SEQ;

DROP TABLE REPEATABILITY_TEST_INPUT;

DROP SEQUENCE REPEATABILITY_TEST_INPUT_SEQ;

DROP TABLE REPEATABILITY_TEST_OUTPUT;

DROP SEQUENCE REPEATABILITY_TEST_OUTPUT_SEQ;

DROP TABLE ORV;

DROP SEQUENCE ORV_SEQ;

DROP TABLE ORV_ALLOCATION;

DROP SEQUENCE ORV_ALLOCATION_SEQ;

DROP TABLE DIVERSION_ORV;

DROP SEQUENCE DIVERSION_ORV_SEQ;

DROP TABLE DIVERSION_ORV_ALLOCATION;

DROP SEQUENCE DIVERSION_ORV_ALLOCATION_SEQ;

DROP TABLE CASH_RELEASED;

DROP SEQUENCE CASH_RELEASED_SEQ;

DROP TABLE FAKE_NOTE;

DROP SEQUENCE FAKE_NOTE_SEQ;

DROP TABLE ACCOUNT_DETAIL;

DROP SEQUENCE ACCOUNT_DETAIL_SEQ;

DROP TABLE DELEGATE_RIGHT;

DROP SEQUENCE DELEGATE_SEQ;

DROP TABLE DISCREPANCY;

DROP SEQUENCE DISCREPANCY_SEQ;

DROP TABLE DISCREPANCY_ALLOCATION;

DROP SEQUENCE DISCREPANCY_ALLOCATION_SEQ;

DROP TABLE MACHINE;

DROP SEQUENCE MACHINE_SEQ;

DROP TABLE MACHINE_MODEL;

DROP SEQUENCE MACHINE_MODEL_SEQ;

DROP TABLE MACHINE_SOFTWARE_UPDATION;

DROP SEQUENCE MACHINE_SOFTWARE_UPDATION_SEQ;

DROP TABLE MACHINE_DOWNTIME_UPDATION;

DROP SEQUENCE MACHINE_DOWNTIME_UPDATION_SEQ;

DROP TABLE UI_ROLE;

DROP TABLE UI_ROLE_PERMISSION;

DROP TABLE CRA_ACCOUNT_DETAIL;

DROP SEQUENCE CRA_ACCOUNT_DETAIL_SEQ;

DROP TABLE DSB_ACCOUNT_DETAIL;

DROP SEQUENCE DSB_ACCOUNT_DETAIL_SEQ;

DROP TABLE RBI_MASTER;

DROP SEQUENCE RBI_MASTER_SEQ;

DROP TABLE CRA;

DROP SEQUENCE CRA_SEQ;

DROP TABLE CRA_ALLOCATION;

DROP SEQUENCE CRA_ALLOCATION_SEQ;

DROP TABLE MACHINE_COMPANY;

DROP SEQUENCE MACHINE_COMPANY_SEQ;

DROP TABLE BANK_RECEIPT;

DROP SEQUENCE BANK_RECEIPT_SEQ;

DROP TABLE OTHER_BANK;

DROP SEQUENCE OTHER_BANK_SEQ;

DROP TABLE OTHER_BANK_ALLOCATION;

DROP SEQUENCE OTHER_BANK_ALLOCATION_SEQ;

DROP TABLE UI_USER_PASSWORD_RESET;

DROP TABLE COINS_SEQUENCE;

DROP SEQUENCE COINS_SEQUENCE_SEQ;

DROP VIEW ZONE_WISE_SUMMARY;

DROP SEQUENCE ZONE_WISE_SUMMARY_SEQ;

DROP TABLE FORWARD_BUNDLE_FOR_CRA_PAYMENT;

DROP SEQUENCE FORWARD_BUNDLE_CRA_PAYMENT_SEQ;

DROP TABLE PROCESS_BUNDLE_FOR_CRA_PAYMENT;

DROP SEQUENCE PROCESS_BUNDLE_CRA_PAYMENT_SEQ;

DROP TABLE CRA_PAYMENT;

DROP SEQUENCE CRA_PAYMENT_SEQ;

DROP TABLE BOX_MASTER;

DROP SEQUENCE BOX_MASTER_SEQ;

DROP TABLE BIN_TRANSACTION_BOD_BALANCE;

DROP SEQUENCE BIN_TRANSACTION_BOD_BAL_SEQ;

DROP VIEW ZONE_WISE_PR_SUMMARY;

DROP SEQUENCE ZONE_WISE_PR_SUMMARY_SEQ;

DROP VIEW REG_SUMMARY;

DROP SEQUENCE REG_SUMMARY_SEQ;

DROP VIEW REGION_WISE_SUMMARY;

DROP SEQUENCE REGION_WISE_SUMMARY_SEQ;

DROP TABLE ICMC_PRINTER;

DROP SEQUENCE ICMC_PRINTER_SEQ;