--ICMC_PRINTER_ID column added in UI_USER on 4-4-17
ALTER TABLE UI_USER ADD ICMC_PRINTER_ID NUMBER(19,0);

--CURRENT_VERSION column added in BIN_TRANSACTION_BOD_BALANCE on 11-4-17
ALTER TABLE BIN_TRANSACTION_BOD_BALANCE ADD CURRENT_VERSION VARCHAR(40);

--RETURN_BACK_TO_VAULT column added in MACHINE_ALLOCATION on 14-4-17
ALTER TABLE MACHINE_ALLOCATION ADD RETURN_BACK_TO_VAULT NUMBER(19,2);
commit;

--PARENT_ID column added in SAS_ALLOCATION on 30-4-17
ALTER TABLE SAS_ALLOCATION ADD PARENT_ID NUMBER(19);
commit;

--NUMBER_OF_NOTES column added in DISCREPANCY_ALLOCATION on 1-5-17
ALTER TABLE DISCREPANCY_ALLOCATION ADD NUMBER_OF_NOTES NUMBER(11);
commit;

--RECEIPT_SEQUENCE column added in DSB on 20-5-17
ALTER TABLE DSB ADD RECEIPT_SEQUENCE NUMBER(11);
commit;

--RECEIPT_DATE column added in DSB on 22-5-17
ALTER TABLE DSB ADD RECEIPT_DATE date;
commit;

--PRINT_YEAR column added in DISCREPANCY_ALLOCATION on 20-6-17
ALTER TABLE DISCREPANCY_ALLOCATION ADD PRINT_YEAR NUMBER(10);
commit;

--DATE_ON_SHRINK_WRAP column added in DISCREPANCY_ALLOCATION on 20-6-17
ALTER TABLE DISCREPANCY_ALLOCATION ADD DATE_ON_SHRINK_WRAP date;
commit;

--DOWNTIME_REASON column added in MACHINE_DOWNTIME_UPDATION on 11-7-17
ALTER TABLE MACHINE_DOWNTIME_UPDATION ADD DOWNTIME_REASON VARCHAR(45);
commit;


