-- DROP TABLE BIN_CAPACITY_DENOMINATION;

CREATE TABLE BIN_CAPACITY_DENOMINATION (
  ID number(19) NOT NULL,
  VAULT_SIZE varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  MAX_BUNDLE_CAPACITY number(10,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_CAP_DENOM_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BIN_MASTER;

CREATE TABLE BIN_MASTER (
  ID number(19) NOT NULL,
  FIRST_PRIORITY varchar2(250) DEFAULT NULL,
  SECOND_PRIORITY varchar2(250) DEFAULT NULL,
  THIRD_PRIORITY varchar2(250) DEFAULT NULL,
  FOURTH_PRIORITY varchar2(250) DEFAULT NULL,
  FIFTH_PRIORITY varchar2(250) DEFAULT NULL,
  LOCA_PRIORITY number(10) DEFAULT NULL,
  BIN_NUM varchar2(250) DEFAULT NULL,
  IS_ALLOCATED number(10) DEFAULT '0',
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  VAULT_SIZE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BIN_TRANSACTION;

CREATE TABLE BIN_TRANSACTION (
  ID number(19) NOT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  MAX_CAPACITY number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  RECEIVE_BUNDLE number(19,2) DEFAULT NULL,
  BIN_TYPE varchar2(45) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL, 
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PENDING_BUNDLE_REQUEST number(19,2) DEFAULT 0,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  CASH_TYPE varchar2(20) DEFAULT NULL,
  VERIFIED varchar2(20) DEFAULT NULL,
  RBI_ORDER_NO varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BIN_TYPE_COLOR;

CREATE TABLE BIN_TYPE_COLOR (
  ID number(19) NOT NULL,
  BIN_TYPE varchar2(100) DEFAULT NULL,
  COLOR_CODE varchar2(45) DEFAULT NULL,
  HTML_COLOR_CODE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_TYPE_COLOR_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BRANCH;

CREATE TABLE BRANCH (
  ID number(19) NOT NULL,
  SOL_ID varchar2(10) DEFAULT NULL,
  BRANCH_NAME varchar2(100) DEFAULT NULL,
  SERVICING_ICMC varchar2(45) DEFAULT NULL,
  JURISDICTION_ICMC varchar2(45) DEFAULT NULL,
  RBI_NAME varchar2(45) DEFAULT NULL,
  ZONE varchar2(20) DEFAULT NULL,
  REGION varchar2(20) DEFAULT NULL,
  ADDRESS varchar2(250) DEFAULT NULL,
  CITY varchar2(45) DEFAULT NULL,
  PINCODE number(10) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BRANCH_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BRANCH_RECEIPT;

CREATE TABLE BRANCH_RECEIPT (
  ID number(19) NOT NULL,
  SOL_ID varchar2(20) DEFAULT NULL,
  BRANCH varchar2(150) DEFAULT NULL,
  SR_NUMBER varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  FILEPATH varchar2(500) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(150) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  CASH_SOURCE varchar2(45) DEFAULT NULL,
  PENDING_BUNDLE_REQUEST number(19,2) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BRANCH_RECEIPT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CIT_CRA_DRIVER;

CREATE TABLE CIT_CRA_DRIVER (
  ID number(19) NOT NULL,
  VENDOR_NAME varchar2(45) DEFAULT NULL,
  VEHICLE_NUMBER varchar2(45) DEFAULT NULL,
  DRIVER_NAME varchar2(45) DEFAULT NULL,
  LICENSE_NUMBER varchar2(45) DEFAULT NULL,
  LICENSE_ISSUED_STATE varchar2(45) DEFAULT NULL,
  LICENSE_ISSUE_DATE date DEFAULT NULL,
  LICENSE_EXPIRY_DATE date DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CIT_CRA_DRIVER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CIT_CRA_VEHICLE;

CREATE TABLE CIT_CRA_VEHICLE (
  ID number(19) NOT NULL,
  VENDOR_NAME varchar2(45) DEFAULT NULL,
  VEHICLE_NUMBER varchar2(45) DEFAULT NULL,
  BOUGHT_DATE date DEFAULT NULL,
  REGISTRATION_CITY varchar2(45) DEFAULT NULL,
  VEHICLE_INSURANCE varchar2(45) DEFAULT NULL,
  FITNESS_EXPIRY_DATE date DEFAULT NULL,
  POLLUTION_EXPIRY_DATE date DEFAULT NULL,
  PERMIT_DATE date DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CIT_CRA_VEHICLE_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CIT_CRA_VENDOR;

CREATE TABLE CIT_CRA_VENDOR (
  ID number(19) NOT NULL,
  NAME varchar2(45) DEFAULT NULL,
  TYPE_ONE varchar2(45) DEFAULT NULL,
  TYPE_TWO varchar2(45) DEFAULT NULL,
  TYPE_THREE varchar2(45) DEFAULT NULL,
  FPR_NAME varchar2(45) DEFAULT NULL,
  FPR_NUMBER varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  ZONE varchar2(45) DEFAULT NULL,
  REGION varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CIT_CRA_VENDOR_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CIT_CRA_VENDOR_ICMC_ASSO;

CREATE TABLE CIT_CRA_VENDOR_ICMC_ASSO (
  VENDOR_ID number(19) DEFAULT NULL,
  ICMC_ID number(19) DEFAULT NULL
);

-- DROP TABLE DIVERSION_IRV;

CREATE TABLE DIVERSION_IRV (
  ID number(19) NOT NULL,
  ORDER_DATE date DEFAULT NULL,
  RBI_ORDER_NO varchar2(45) DEFAULT NULL,
  EXPIRY_DATE date DEFAULT NULL,
  BANK_NAME varchar2(45) DEFAULT NULL,
  APPROVED_CC varchar2(45) DEFAULT NULL,
  LOCATION varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  CATEGORY varchar2(45) DEFAULT NULL,
  FILEPATH varchar2(245) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DIVERSION_IRV_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DSB;

CREATE TABLE DSB (
  ID number(19) NOT NULL,
  NAME varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  PROCESSING_OR_VAULT varchar2(45) DEFAULT NULL,
  FILEPATH varchar2(245) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DSB_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE FRESH_FROM_RBI;

CREATE TABLE FRESH_FROM_RBI (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  NOTES_OR_COINS varchar2(45) DEFAULT NULL,
  ORDER_DATE date DEFAULT NULL,
  RBI_ORDER_NO varchar2(45) DEFAULT NULL,
  VEHICLE_NUMBER varchar2(45) DEFAULT NULL,
  POTDAR_NAME varchar2(45) DEFAULT NULL,
  ESCORT_OFFICER_NAME varchar2(45) DEFAULT NULL,
  FILEPATH varchar2(245) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  BIN_OR_BOX varchar2(45) DEFAULT NULL,
  POTDAR_STATUS varchar2(45) DEFAULT NULL,
  NO_OF_BAGS number(10) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  CASH_TYPE varchar2(20) DEFAULT NULL,
  PENDING_BUNDLE_REQUEST number(19, 2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE FRESH_FROM_RBI_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE HOLIDAY_MASTER;

CREATE TABLE HOLIDAY_MASTER (
  ID number(10) NOT NULL,
  HOLIDAY_NAME varchar2(110) DEFAULT NULL,
  HOLIDAY_TYPE varchar2(45) DEFAULT NULL,
  HOLIDAY_DATE varchar2(45) DEFAULT NULL,
  ANDAMAN_AND_NICOBAR_ISLANDS varchar2(45) DEFAULT NULL,
  ANDHRA_PRADESH varchar2(45) DEFAULT NULL,
  ARUNACHAL_PRADESH varchar2(45) DEFAULT NULL,
  ASSAM varchar2(45) DEFAULT NULL,
  BIHAR varchar2(45) DEFAULT NULL,
  CHANDIGARH varchar2(45) DEFAULT NULL,
  CHHATTISGARH varchar2(45) DEFAULT NULL,
  DAMAN_AND_DIU varchar2(45) DEFAULT NULL,
  DELHI varchar2(45) DEFAULT NULL,
  GOA varchar2(45) DEFAULT NULL,
  GUJARAT varchar2(45) DEFAULT NULL,
  HIMACHAL_PRADESH varchar2(45) DEFAULT NULL,
  HARYANA varchar2(45) DEFAULT NULL,
  JHARKHAND varchar2(45) DEFAULT NULL,
  JAMMU_AND_KASHMIR varchar2(45) DEFAULT NULL,
  KARNATAKA varchar2(45) DEFAULT NULL,
  KERALA varchar2(45) DEFAULT NULL,
  MAHARASHTRA varchar2(45) DEFAULT NULL,
  MEGHALAYA varchar2(45) DEFAULT NULL,
  MANIPUR varchar2(45) DEFAULT NULL,
  MADHYA_PRADESH varchar2(45) DEFAULT NULL,
  MIZORAM varchar2(45) DEFAULT NULL,
  NAGALAND varchar2(45) DEFAULT NULL,
  ORISSA varchar2(45) DEFAULT NULL,
  PUNJAB varchar2(45) DEFAULT NULL,
  PONDICHERRY varchar2(45) DEFAULT NULL,
  RAJASTHAN varchar2(45) DEFAULT NULL,
  SIKKIM varchar2(45) DEFAULT NULL,
  TAMIL_NADU varchar2(45) DEFAULT NULL,
  TRIPURA varchar2(45) DEFAULT NULL,
  UTTAR_PRADESH varchar2(45) DEFAULT NULL,
  UTTARANCHAL varchar2(45) DEFAULT NULL,
  WEST_BENGAL varchar2(45) DEFAULT NULL,
  DADRA_AND_NAGAR_HAVELI varchar2(45) DEFAULT NULL,
  LAKSHADWEEP varchar2(45) DEFAULT NULL,
  TELANGANA varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE HOLIDAY_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ICMC;

CREATE TABLE ICMC (
  ID number(19) NOT NULL,
  NAME varchar2(45) DEFAULT NULL,
  LINK_BRANCH_SOLID varchar2(45) DEFAULT NULL,
  RBI_NAME varchar2(45) DEFAULT NULL,
  ADDRESS varchar2(250) DEFAULT NULL,
  ZONE varchar2(45) DEFAULT NULL,
  REGION varchar2(45) DEFAULT NULL,
  CITY varchar2(45) DEFAULT NULL,
  PINCODE number(10) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ICMC_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ICMC_REPORT;

CREATE TABLE ICMC_REPORT (
  ID number(10) NOT NULL,
  CUSTOM_REPORT_TYPE varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  REASON_FOR_DELETION varchar2(45) DEFAULT NULL,
  APPROVAL_FOR_DELETION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ICMC_REPORT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ICMC_REPORT_ASSOCIATION;

CREATE TABLE ICMC_REPORT_ASSOCIATION (
  REPORT_ID number(10) DEFAULT NULL,
  REPORT_TYPE varchar2(45) DEFAULT NULL
);

CREATE SEQUENCE ICMC_REPORT_ASSOCIATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE INDENT;

CREATE TABLE INDENT (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  DESCRIPTION varchar2(500) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CASH_SOURCE varchar2(45) DEFAULT NULL,
  PENDING_BUNDLE_REQUEST number(19,2) DEFAULT 0,
  BIN_CATEGORY_TYPE varchar2(45) DEFAULT NULL,
  RBI_ORDER_NO varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE INDENT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE JURISDICTION;

CREATE TABLE JURISDICTION (
  ID number(10) NOT NULL,
  SOL_ID number(10) DEFAULT NULL,
  BRANCH_NAME varchar2(45) DEFAULT NULL,
  ICMC_NAME varchar2(45) DEFAULT NULL,
  JURISDICTION varchar2(45) DEFAULT NULL,
  CITY varchar2(45) DEFAULT NULL,
  PINCODE number(10) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE JURISDICTION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE MACHINE_ALLOCATION;

CREATE TABLE MACHINE_ALLOCATION (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  ISSUED_BUNDLE number(19,2) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  CASH_SOURCE varchar2(45) DEFAULT NULL,
  IS_MANUAL varchar2(45) DEFAULT NULL,
  PENDING_BUNDLE number(19,2) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE PROCESS;

CREATE TABLE PROCESS (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS number(10) DEFAULT '1',
  FILEPATH varchar2(250) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  PROCESSED_BY varchar2(20) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE PROCESS_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE SAS;

CREATE TABLE SAS (
  ID number(19) NOT NULL,
  SR_NO varchar2(45) DEFAULT NULL,
  SOL_ID varchar2(20) DEFAULT NULL,
  BRANCH varchar2(250) DEFAULT NULL,
  TOTAL_VALUE number(19,2) DEFAULT NULL,
  TOTAL_VALUE_OF_COINS_RS_10 number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_COINS_RS_5 number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_COINS_RS_2 number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_COINS_RS_1 number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_1_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_10_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_100_F number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_1000_F number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_2_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_20_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_5_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_50_F number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_500_F number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_1_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_10_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_100_I number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_1000_I number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_2_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_20_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_50_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_5_I number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_500_I number(12,2) DEFAULT '0.00',
  DATE_OF_DISPATCH varchar2(45) DEFAULT NULL,
  ACTION_TAKEN varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  STATUS number(10) DEFAULT '1',
  ICMC_ID number(10,0) DEFAULT NULL,
  RELEASED_NOTES_1_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_1_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_10_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_10_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_100_I number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_100_F number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_1000_I number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_1000_F number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_2_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_2_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_20_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_20_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_5_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_5_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_50_I number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_50_F number(10,2) DEFAULT '0.00',
  RELEASED_NOTES_500_I number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_500_F number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_100_A number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_500_A number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_1000_A number(12,2) DEFAULT '0.00',
  FILE_NAME varchar2(45) DEFAULT NULL,
  RELEASED_NOTES_100_A number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_500_A number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_1000_A number(12,2) DEFAULT '0.00',
  ENABLE_DISABLE number(10) DEFAULT NULL,
  RELEASED_COINS_1 number(10,2) DEFAULT '0.00',
  RELEASED_COINS_2 number(10,2) DEFAULT '0.00',
  RELEASED_COINS_5 number(10,2) DEFAULT '0.00',
  RELEASED_COINS_10 number(10,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_2000_I number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_2000_A number(12,2) DEFAULT '0.00',
  TOTAL_VALUE_OF_NOTES_RS_2000_F number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_2000_A number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_2000_I number(12,2) DEFAULT '0.00',
  RELEASED_NOTES_2000_F number(12,2) DEFAULT '0.00',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SAS_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE SAS_ALLOCATION;

CREATE TABLE SAS_ALLOCATION (
  ID number(19) NOT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  BIN_TYPE varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CASH_TYPE varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SAS_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE SERVICING_BRANCH;

CREATE TABLE SERVICING_BRANCH (
  ID number(19) NOT NULL,
  ICMC_NAME varchar2(45) DEFAULT NULL,
  SOL_ID number(10) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  RBI_JI varchar2(45) DEFAULT NULL,
  RBI_SI varchar2(45) DEFAULT NULL,
  CATEGORY varchar2(45) DEFAULT NULL,
  RBI_ICMC varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SERVICING_BRANCH_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE SOILED_REMITTANCE;

CREATE TABLE SOILED_REMITTANCE (
  ID number(19) NOT NULL,
  ORDER_DATE date DEFAULT NULL,
  REMITTANCE_ORDER_NO number(19,0) DEFAULT NULL,
  APPROVED_REMITTANCE_DATE date DEFAULT NULL,
  NOTES varchar2(45) DEFAULT NULL,
  TYPES varchar2(45) DEFAULT NULL,
  VEHICLE_NUMBER varchar2(45) DEFAULT NULL,
  LOCATION varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,2) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SOILED_REMITTANCE_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE SOILED_REMITTANCE_ALLOCATION;

CREATE TABLE SOILED_REMITTANCE_ALLOCATION (
  ID number(19) NOT NULL,
  SOILED_REMITTANCE_ID number(19) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  BOX varchar2(45) DEFAULT NULL,
  WEIGHT varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  FILEPATH varchar2(500) DEFAULT NULL,
  PENDING_BUNDLE number(19,2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SOILED_REMIT_ALLOC_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE UI_USER;

CREATE TABLE UI_USER (
  ID varchar2(32) NOT NULL,
  NAME varchar2(45) NOT NULL,
  PASSWORD varchar2(250) DEFAULT NULL,
  PASSWORD_HASH varchar2(45) DEFAULT NULL,
  PASSWORD_SALT varchar2(45) DEFAULT NULL,
  ZONE_ID varchar2(45) DEFAULT NULL,
  REGION_ID varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  CREATED_BY varchar2(45) DEFAULT NULL,
  UPDATED_BY varchar2(45) DEFAULT NULL,
  CREATED_DATETIME timestamp(0) DEFAULT NULL NULL,
  UPDATED_DATETIME timestamp(0) DEFAULT NULL NULL,
  LAST_AUTH_OK varchar2(45) DEFAULT NULL,
  LAST_AUTH_FAIL timestamp(0) DEFAULT NULL NULL,
  FAILED_LOGONS number(10) DEFAULT NULL,
  EMAIL varchar2(45) DEFAULT NULL,
  ROLE_ID varchar2(45) DEFAULT NULL,
  IS_ACCOUNT_LOCKED char(1) DEFAULT NULL,
  PRIMARY KEY (ID)
);

-- DROP TABLE VENDOR;

CREATE TABLE VENDOR (
  ID number(19) NOT NULL,
  NAME varchar2(45) DEFAULT NULL,
  ADDRESS varchar2(45) DEFAULT NULL,
  LOCATION varchar2(45) DEFAULT NULL,
  CITY varchar2(45) DEFAULT NULL,
  PINCODE number(10) DEFAULT NULL,
  PHONE_NUMBER number(19) DEFAULT NULL,
  EMAIL_ID varchar2(45) DEFAULT NULL,
  PF_REG_NUMBER varchar2(45) DEFAULT NULL,
  ESIC_REG_NUMBER varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE VENDOR_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ZONE_MASTER;

CREATE TABLE ZONE_MASTER (
  ID number(19) NOT NULL,
  ZONE varchar2(45) DEFAULT NULL,
  REGION varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ZONE_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE FRESH_CURRENCY;

CREATE TABLE FRESH_CURRENCY (
  ID number(19) NOT NULL,
  MACHINE_NO varchar2(45) DEFAULT NULL,
  DENOMINATION number(10,0) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  TOTAL_VALUE number(19,2) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE FRESH_CURRENCY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ASSIGN_VAULT_CUSTODIAN;

CREATE TABLE ASSIGN_VAULT_CUSTODIAN (
  ID number(19) NOT NULL,
  USER_ID varchar2(45) DEFAULT NULL,
  CUSTODIAN varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ASSIGN_VAULT_CUSTODIAN_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE KEY_SET;

CREATE TABLE KEY_SET (
  ID number(19) NOT NULL,
  CUSTODIAN varchar2(45) DEFAULT NULL,
  KEY_NUMBER varchar2(45) DEFAULT NULL,
  LOCATION_OF_LOCK varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE KEY_SET_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE REPEATABILITY_TEST_INPUT;

CREATE TABLE REPEATABILITY_TEST_INPUT (
  ID number(19) NOT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  MACHINE_SERIAL_NO varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  DENOMINATION varchar2(45) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  BIN_NO varchar2(45) DEFAULT NULL,
  TOTAL_NOTES number(19,2) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE REPEATABILITY_TEST_INPUT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE REPEATABILITY_TEST_OUTPUT;

CREATE TABLE REPEATABILITY_TEST_OUTPUT (
  ID number(19) NOT NULL,
  MACHINE_NO varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  DENOMINATION varchar2(45) DEFAULT NULL,
  BUNDLE varchar2(45) DEFAULT NULL,
  TOTAL_VALUE varchar2(45) DEFAULT NULL,
  BIN_NO varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  TYPEVALUE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE REPEATABILITY_TEST_OUTPUT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ORV;

CREATE TABLE ORV (
  ID number(19) NOT NULL,
  SR varchar2(45) DEFAULT NULL,
  SACK_LOCK_NUMBER varchar2(45) DEFAULT NULL,
  SOL_ID varchar2(20) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  VENDOR varchar2(45) DEFAULT NULL,
  CUSTODIAN varchar2(45) DEFAULT NULL,
  VEHICLE varchar2(45) DEFAULT NULL,
  STATUS number(10) DEFAULT '1',
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ORV_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ORV_ALLOCATION;

CREATE TABLE ORV_ALLOCATION (
  ID number(19) NOT NULL,
  ORV_ID number(19) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ORV_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DIVERSION_ORV;

CREATE TABLE DIVERSION_ORV (
  ID number(19) NOT NULL,
  ORDER_DATE date DEFAULT NULL,
  RBI_ORDER_NO number(10) DEFAULT NULL,
  EXPIRY_DATE date DEFAULT NULL,
  BANK_NAME varchar2(45) DEFAULT NULL,
  APPROVED_CC varchar2(45) DEFAULT NULL,
  LOCATION varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DIVERSION_ORV_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DIVERSION_ORV_ALLOCATION;

CREATE TABLE DIVERSION_ORV_ALLOCATION (
  ID number(19) NOT NULL,
  DIVERSION_ORV_ID number(19) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  CATEGORY varchar2(45) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  PENDING_BUNDLE number(19,2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DIVERSION_ORV_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CASH_RELEASED;

CREATE TABLE CASH_RELEASED (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  SOL_ID number(19) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CASH_RELEASED_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE FAKE_NOTE;

CREATE TABLE FAKE_NOTE (
  ID number(19) NOT NULL,
  FAKE_NOTE_DATE date DEFAULT NULL,
  SOL_ID number(10) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  FAKE_NOTE_SERIAL_NUMBER varchar2(45) DEFAULT NULL,
  CUST_TELLER_CAM varchar2(45) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE FAKE_NOTE_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ACCOUNT_DETAIL;

CREATE TABLE ACCOUNT_DETAIL (
  ID number(19) NOT NULL,
  ACTIVITY varchar2(45) DEFAULT NULL,
  USAGE varchar2(45) DEFAULT NULL,
  DEBIT_OR_CREDIT varchar2(45) DEFAULT NULL,
  ACCOUNT_DETAILS varchar2(45) DEFAULT NULL,
  BRANCH_DETAILS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ACCOUNT_DETAIL_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DELEGATE_RIGHT;

CREATE TABLE DELEGATE_RIGHT (	
  ID NUMBER(*,0) NOT NULL ENABLE, 
 	USER_ID VARCHAR2(45 BYTE) DEFAULT NULL, 
	ROLE VARCHAR2(45 BYTE) DEFAULT NULL,
	STATUS VARCHAR2(45 BYTE) DEFAULT NULL,
	PERIOD_FROM DATE DEFAULT NULL, 
	PERIOD_TO DATE DEFAULT NULL, 
	ICMC_ID NUMBER(19,0) DEFAULT NULL, 
	INSERT_BY VARCHAR2(45 BYTE) DEFAULT NULL, 
	UPDATE_BY VARCHAR2(45 BYTE) DEFAULT NULL, 
	INSERT_TIME TIMESTAMP (6) DEFAULT NULL, 
	UPDATE_TIME TIMESTAMP (6) DEFAULT NULL
);
             
CREATE SEQUENCE DELEGATE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

-- DROP TABLE DISCREPANCY;

CREATE TABLE DISCREPANCY (
  ID number(19) NOT NULL,
  MACHINE_NUMBER number(10) DEFAULT NULL,
  DISCREPANCY_DATE date DEFAULT NULL,
  SOL_ID number(10) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  FILE_PATH varchar2(500) DEFAULT NULL,
  ACCOUNT_TELLER_CAM varchar2(45) DEFAULT NULL,
  CUSTOMER_NAME varchar2(45) DEFAULT NULL,
  DISCREPANCY_TYPE varchar2(45) DEFAULT NULL,
  MUTIL_TYPE varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DISCREPANCY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DISCREPANCY_ALLOCATION;

CREATE TABLE DISCREPANCY_ALLOCATION (
  ID NUMBER(*,0) NOT NULL ENABLE,
  DISCREPANCY_ID NUMBER(19,0) DEFAULT NULL,
  DENOMINATION NUMBER(11) DEFAULT NULL,
  NOTE_SERIAL_NUMBER VARCHAR2(45) DEFAULT NULL,
  DIS_VALUE NUMBER(11) DEFAULT NULL,
  SR_NUMBER VARCHAR2(45) DEFAULT NULL,
  INSERT_TIME TIMESTAMP (6) DEFAULT NULL,
  UPDATE_TIME TIMESTAMP (6) DEFAULT NULL,
  INSERT_BY VARCHAR2(45) DEFAULT NULL,
  UPDATE_BY VARCHAR2(45) DEFAULT NULL,
  ICMC_ID NUMBER(19,0) DEFAULT NULL,
  REMARKS varchar2(45) DEFAULT NULL,
  DISCREPANCY_TYPE varchar2(45) DEFAULT NULL,
  MUTIL_TYPE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE  DISCREPANCY_ALLOCATION_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

-- DROP TABLE MACHINE;

CREATE TABLE MACHINE (
  ID number(19) NOT NULL,
  COMPANY_NAME varchar2(45) DEFAULT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  PURCHASE_DATE date DEFAULT NULL,
  ASSET_CODE varchar2(45) DEFAULT NULL,
  MACHINE_SI_NO varchar2(45) DEFAULT NULL,
  MODEL_TYPE varchar2(45) DEFAULT NULL,
  STANDARD_PRODUCTIVITY varchar2(45) DEFAULT NULL,
  INSERT_TIME date DEFAULT NULL,
  UPDATE_TIME date DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  SAP number(10) DEFAULT NULL,
  MAP number(10) DEFAULT NULL,
  OSAP number(10) DEFAULT NULL,
  PM_DATE date DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE MACHINE_MODEL;

CREATE TABLE MACHINE_MODEL (
  ID number(19) NOT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  MACHINE_MODEL_TYPE varchar2(45) DEFAULT NULL,
  STANDARD_PRODUCTIVITY varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_MODEL_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE MACHINE_SOFTWARE_UPDATION;

CREATE TABLE MACHINE_SOFTWARE_UPDATION (
  ID number(19) NOT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  SAP number(10) DEFAULT NULL,
  MAP number(10) DEFAULT NULL,
  OSAP number(10) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  ASSET_CODE varchar2(45) DEFAULT NULL,
  MACHINE_SI_NO varchar2(45) DEFAULT NULL,
  MODEL_TYPE varchar2(45) DEFAULT NULL,
  STANDARD_PRODUCTIVITY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_SOFTWARE_UPDATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE MACHINE_DOWNTIME_UPDATION;

CREATE TABLE MACHINE_DOWNTIME_UPDATION (
  ID number(19) NOT NULL,
  MACHINE_DOWN_DATE_FROM timestamp(0) DEFAULT NULL,
  MACHINE_NO number(10) DEFAULT NULL,
  MACHINE_DOWN_DATE_TO timestamp(0) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  REMARKS varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_DOWNTIME_UPDATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE UI_ROLE;

CREATE TABLE UI_ROLE (
  ID varchar2(32) NOT NULL,
  ICMC_ACCESS varchar2(45) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  CREATED_BY varchar2(45) DEFAULT NULL,
  UPDATED_BY varchar2(45) DEFAULT NULL,
  CREATED_DATETIME timestamp(0) DEFAULT NULL NULL,
  UPDATED_DATETIME timestamp(0) DEFAULT NULL NULL,
  PRIMARY KEY (ID)
);

-- DROP TABLE UI_ROLE_PERMISSION;

CREATE TABLE UI_ROLE_PERMISSION (
  ROLE_NAME VARCHAR2(32) NOT NULL,
  FUNCTION_PERMISSION varchar2(45) DEFAULT NULL
);

-- DROP TABLE CRA_ACCOUNT_DETAIL;

CREATE TABLE CRA_ACCOUNT_DETAIL (
  ID number(19) NOT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CRA_VENDOR_NAME varchar2(45) DEFAULT NULL,
  MSP_NAME varchar2(45) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CRA_ACCOUNT_DETAIL_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE DSB_ACCOUNT_DETAIL;

CREATE TABLE DSB_ACCOUNT_DETAIL (
  ID number(19) NOT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  DSB_VENDOR_NAME varchar2(45) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE DSB_ACCOUNT_DETAIL_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE RBI_MASTER;

CREATE TABLE RBI_MASTER (
  ID number(19) NOT NULL,
  RBI_NAME varchar2(45) NOT NULL,
  ZONE varchar2(45) DEFAULT NULL,
  REGION varchar2(45) DEFAULT NULL,
  STATE varchar2(45) DEFAULT NULL,
  CITY varchar2(45) DEFAULT NULL,
  ADDRESS varchar2(80) DEFAULT NULL,
  PIN_NO number(10,0) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE RBI_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CRA;

CREATE TABLE CRA (
  ID number(19) NOT NULL,
  SR_NO varchar2(45) DEFAULT NULL,
  SOL_ID varchar2(45) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  VENDOR varchar2(45) DEFAULT NULL,
  MSP_NAME varchar2(45) DEFAULT NULL,
  ACCOUNT_NUMBER varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CRA_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CRA_ALLOCATION;

CREATE TABLE CRA_ALLOCATION (
  ID number(19) NOT NULL,
  CRA_ID number(19) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  VAULT number(19,2) DEFAULT NULL,
  FORWARD number(19,2) DEFAULT NULL,
  PENDING_REQUESTED_BUNDLE number(19,2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE CRA_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE MACHINE_COMPANY;

CREATE TABLE MACHINE_COMPANY (
  ID number(19) NOT NULL,
  COMPANY_NAME varchar2(45) DEFAULT NULL,
  EMAIL varchar2(45) DEFAULT NULL,
  PURCHASE_DATE date DEFAULT NULL,
  PHONE_NUMBER number(19) DEFAULT NULL,
  ADDRESS varchar2(80) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  INSERT_TIME timestamp(3) DEFAULT NULL,
  UPDATE_TIME timestamp(3) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE MACHINE_COMPANY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BANK_RECEIPT;

CREATE TABLE BANK_RECEIPT (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE NUMBER(10,2) DEFAULT NULL,
  TOTAL NUMBER(19,2) DEFAULT NULL,
  BIN_NUM varchar2(20) DEFAULT NULL,
  FILE_PATH VARCHAR2(500) DEFAULT NULL,
  ICMC_ID NUMBER(19,0) DEFAULT NULL,
  STATUS NUMBER(10) DEFAULT NULL,
  BANK_NAME VARCHAR2(45) DEFAULT NULL,
  RTGS_UTR_NO varchar2(45) DEFAULT NULL,
  SOL_ID VARCHAR2(20) DEFAULT NULL,
  BRANCH VARCHAR2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BANK_RECEIPT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE OTHER_BANK;

CREATE TABLE OTHER_BANK (
  ID number(19) NOT NULL,
  BANK_NAME varchar2(45) DEFAULT NULL,
  RTGS_UTR_NO varchar2(45) DEFAULT NULL,
  SOL_ID varchar2(45) DEFAULT NULL,
  BRANCH varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE OTHER_BANK_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE OTHER_BANK_ALLOCATION;

CREATE TABLE OTHER_BANK_ALLOCATION (
  ID number(19) NOT NULL,
  OTHER_BANK_ID number(19) DEFAULT NULL,
  DENOMINATION number(19) DEFAULT NULL,
  BUNDLE number(19,2) DEFAULT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  ICMC_ID number(19) DEFAULT NULL,
  TOTAL number(19,2) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PENDING_BUNDLE number(19,2) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE OTHER_BANK_ALLOCATION_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE UI_USER_PASSWORD_RESET;

CREATE TABLE UI_USER_PASSWORD_RESET (
  USER_ID varchar2(32) NOT NULL,
  TOKEN varchar2(45) NOT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  CREATED_BY varchar2(45) DEFAULT NULL,
  UPDATED_BY varchar2(45) DEFAULT NULL,
  CREATED_DATETIME timestamp(0) DEFAULT NULL NULL,
  UPDATED_DATETIME timestamp(0) DEFAULT NULL NULL
);

-- DROP TABLE COINS_SEQUENCE;

CREATE TABLE COINS_SEQUENCE (
  ID number(19) NOT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  SEQUENCE number(19) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE COINS_SEQUENCE_SEQ START WITH 1 INCREMENT BY 1;

-- DROP VIEW ZONE_WISE_SUMMARY;

CREATE VIEW ZONE_WISE_SUMMARY AS SELECT ROW_NUMBER() OVER (ORDER BY BIN_TYPE) AS ID, 
SUM(TOTAL) AS TOTAL_VALUE, BIN_TYPE, ZONE FROM (SELECT SUM(RECEIVE_BUNDLE),  
DENOMINATION* SUM(RECEIVE_BUNDLE)*1000 AS TOTAL, DENOMINATION, BIN_TYPE, ZONE FROM BIN_TRANSACTION, ICMC ICMC1 
WHERE ICMC_ID IN (SELECT ID FROM ICMC WHERE ZONE IN (SELECT DISTINCT ZONE FROM ZONE_MASTER) AND CASH_TYPE='NOTES')
and ICMC_ID = ICMC1.id
GROUP BY DENOMINATION, BIN_TYPE, ZONE
ORDER BY BIN_TRANSACTION.DENOMINATION) GROUP BY BIN_TYPE, ZONE;

CREATE SEQUENCE ZONE_WISE_SUMMARY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE FORWARD_BUNDLE_FOR_CRA_PAYMENT;

CREATE TABLE FORWARD_BUNDLE_FOR_CRA_PAYMENT (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PENDING_REQUESTED_BUNDLE number(19,2) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE FORWARD_BUNDLE_CRA_PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE PROCESS_BUNDLE_FOR_CRA_PAYMENT;

CREATE TABLE PROCESS_BUNDLE_FOR_CRA_PAYMENT (
  ID number(19) NOT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  FILEPATH varchar2(500) DEFAULT NULL,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  PENDING_REQUESTED_BUNDLE number(19,2) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE PROCESS_BUNDLE_CRA_PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE CRA_PAYMENT;

CREATE TABLE CRA_PAYMENT (
  ID number(19) NOT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  BIN_TYPE varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  BUNDLE number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  primary key (id)
);

CREATE SEQUENCE CRA_PAYMENT_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BOX_MASTER;

CREATE TABLE BOX_MASTER (
  ID number(19) NOT NULL,
  BOX_NAME varchar2(45) DEFAULT NULL,
  MAX_CAPACITY number(10,0) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  IS_ALLOCATED number(10) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  CURRENCY_TYPE varchar2(45) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BOX_MASTER_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE BIN_TRANSACTION_BOD_BALANCE;

CREATE TABLE BIN_TRANSACTION_BOD_BALANCE (
  ID number(19) NOT NULL,
  DENOMINATION_1 number(10,2) DEFAULT NULL,
  DENOMINATION_2 number(10,2) DEFAULT NULL,
  DENOMINATION_5 number(10,2) DEFAULT NULL,
  DENOMINATION_10 number(10,2) DEFAULT NULL,
  DENOMINATION_20 number(10,2) DEFAULT NULL,
  DENOMINATION_50 number(10,2) DEFAULT NULL,
  DENOMINATION_100 number(10,2) DEFAULT NULL,
  DENOMINATION_500 number(10,2) DEFAULT NULL,
  DENOMINATION_1000 number(10,2) DEFAULT NULL,
  DENOMINATION_2000 number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  CASH_TYPE varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_TRANSACTION_BOD_BAL_SEQ START WITH 1 INCREMENT BY 1;

-- DROP VIEW ZONE_WISE_PR_SUMMARY;

CREATE VIEW ZONE_WISE_PR_SUMMARY AS SELECT ROW_NUMBER() OVER (ORDER BY DENOMINATION) AS ID, 
SUM(TOTAL) AS TOTAL_VALUE, ZONE FROM (SELECT SUM(PENDING_BUNDLE),  
DENOMINATION* SUM(PENDING_BUNDLE)*1000 AS TOTAL, DENOMINATION, ZONE FROM MACHINE_ALLOCATION, ICMC ICMC1 
WHERE ICMC_ID IN (SELECT ID FROM ICMC WHERE ZONE IN (SELECT DISTINCT ZONE FROM ZONE_MASTER))
and ICMC_ID = ICMC1.id
GROUP BY DENOMINATION, ZONE
ORDER BY MACHINE_ALLOCATION.DENOMINATION) GROUP BY DENOMINATION, ZONE;

CREATE SEQUENCE ZONE_WISE_PR_SUMMARY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP VIEW REG_SUMMARY;

CREATE VIEW REG_SUMMARY AS SELECT ROW_NUMBER() OVER (ORDER BY BIN_TYPE) AS ID, 
SUM(TOTAL) AS TOTAL_VALUE, BIN_TYPE, REGION FROM (SELECT SUM(RECEIVE_BUNDLE),  
DENOMINATION* SUM(RECEIVE_BUNDLE)*1000 AS TOTAL, DENOMINATION, BIN_TYPE, REGION FROM BIN_TRANSACTION, ICMC ICMC1 
WHERE ICMC_ID IN (SELECT ID FROM ICMC WHERE REGION IN 
(SELECT DISTINCT REGION FROM ZONE_MASTER WHERE ZONE IN (SELECT DISTINCT ZONE FROM ZONE_MASTER)))
and ICMC_ID = ICMC1.id
GROUP BY DENOMINATION, BIN_TYPE, REGION
ORDER BY BIN_TRANSACTION.DENOMINATION) GROUP BY BIN_TYPE, REGION;

CREATE SEQUENCE REG_SUMMARY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP VIEW REGION_WISE_SUMMARY;

CREATE VIEW REGION_WISE_SUMMARY AS SELECT ROW_NUMBER() OVER (ORDER BY BIN_TYPE) AS ID, 
SUM(TOTAL_VALUE) AS TOTAL_VALUE, BIN_TYPE, ZONE, REGION,cash_type FROM(
SELECT  
SUM(TOTAL) AS TOTAL_VALUE, BIN_TYPE, ZONE, REGION,cash_type FROM (SELECT SUM(RECEIVE_BUNDLE),  
case 
when cash_type='NOTES' then DENOMINATION* SUM(RECEIVE_BUNDLE)*1000
when cash_type='COINS' and  DENOMINATION = 1 or DENOMINATION = 2 or DENOMINATION = 5 then DENOMINATION* SUM(RECEIVE_BUNDLE)*2500
when cash_type='COINS' and  DENOMINATION = 10 then DENOMINATION* SUM(RECEIVE_BUNDLE)*2000 
end
AS TOTAL,
DENOMINATION,
cash_type,
case when cash_type='COINS' then 'COINS' else BIN_TYPE end as BIN_TYPE, ZONE, REGION FROM BIN_TRANSACTION, ICMC ICMC1 
WHERE ICMC_ID IN (SELECT ID FROM ICMC WHERE ZONE IN (SELECT DISTINCT ZONE FROM ZONE_MASTER))
and ICMC_ID = ICMC1.id
GROUP BY DENOMINATION, BIN_TYPE,cash_type, ZONE, REGION
ORDER BY BIN_TRANSACTION.DENOMINATION) GROUP BY BIN_TYPE, cash_type, ZONE, REGION

union

SELECT  
SUM(TOTAL) AS TOTAL_VALUE, BIN_TYPE, ZONE, REGION,cash_type FROM (SELECT SUM(PENDING_BUNDLE),  
'NOTES' as cash_type, 'UNPROCESS' as BIN_TYPE, DENOMINATION* SUM(PENDING_BUNDLE)*1000 AS TOTAL,
DENOMINATION, ZONE, REGION FROM machine_allocation, ICMC ICMC1 
WHERE ICMC_ID IN (SELECT ID FROM ICMC WHERE ZONE IN (SELECT DISTINCT ZONE FROM ZONE_MASTER))
and ICMC_ID = ICMC1.id
GROUP BY DENOMINATION, 'UNPROCESS','NOTES', ZONE, REGION
ORDER BY machine_allocation.DENOMINATION) GROUP BY BIN_TYPE, cash_type, ZONE, REGION
)GROUP BY BIN_TYPE, cash_type, ZONE, REGION;


CREATE SEQUENCE REGION_WISE_SUMMARY_SEQ START WITH 1 INCREMENT BY 1;

-- DROP TABLE ICMC_PRINTER;

CREATE TABLE ICMC_PRINTER (
  ID number(19) NOT NULL,
  PRINTER_NAME varchar2(45) DEFAULT NULL,
  PRINTER_IP varchar2(45) DEFAULT NULL,
  PORT number(19,0) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  STATUS varchar2(45) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE ICMC_PRINTER_SEQ START WITH 1 INCREMENT BY 1;



CREATE TABLE BIN_TRANSACTION_HISTORY (
  ID number(19) NOT NULL,
  BIN_NUM varchar2(45) DEFAULT NULL,
  DENOMINATION number(10) DEFAULT NULL,
  MAX_CAPACITY number(10,2) DEFAULT NULL,
  INSERT_TIME timestamp(0) DEFAULT NULL,
  RECEIVE_BUNDLE number(19,2) DEFAULT NULL,
  BIN_TYPE varchar2(45) DEFAULT NULL,
  STATUS varchar2(20) DEFAULT NULL, 
  UPDATE_TIME timestamp(0) DEFAULT NULL,
  INSERT_BY varchar2(45) DEFAULT NULL,
  UPDATE_BY varchar2(45) DEFAULT NULL,
  ICMC_ID number(19,0) DEFAULT NULL,
  PENDING_BUNDLE_REQUEST number(19,2) DEFAULT 0,
  CASH_SOURCE varchar2(20) DEFAULT NULL,
  BIN_CATEGORY_TYPE varchar2(20) DEFAULT NULL,
  CASH_TYPE varchar2(20) DEFAULT NULL,
  VERIFIED varchar2(20) DEFAULT NULL,
  RBI_ORDER_NO varchar2(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE BIN_TRANSACTION_HISTORY_SEQ START WITH 1 INCREMENT BY 1;

